### ISSUE TITLE
add cxxnet into convnet-benchmarks

### ISSUE THREAD

**Issue by mli** [dmlc/cxxnet#104]
link: https://github.com/soumith/convnet-benchmarks
i saw cxxnet there, but didn't find the results. it would be very nice if we can have some numbers there.

**Comment by winstywang** [comment]
Our method is based on cuDNN, so I don't think there will be a difference between the one reported as cuDNN.

**Comment by antinucleon** [comment]
Do you think it worth to add newest Maxwell conv to cxxnet? it is 2 times
faster than cudnn, but only support maxwell gpu

**Comment by mli** [comment]
that will be fantastic. all of my gpus are maxwell. btw, 980 ti will come out soon
