### ISSUE TITLE
SaveModel and LoadModel for SGD with momentum

### ISSUE THREAD

**Issue by zhongwen** [dmlc/cxxnet#117]
I met NaN problems occasionally during the training process as reported in [Kaggle-NDSB](https://github.com/auroraxie/Kaggle-NDSB) by @auroraxie. So, I need to resume from previous training process if NaN happens.

However, it seems that SaveModel and LoadModel functions in the layers with learnable parameters did not consider the historical gradients [m_w](https://github.com/dmlc/cxxnet/blob/master/src/updater/sgd_updater-inl.hpp#L78) for the updaters, e.g. SGD, NAG. Without saving historical gradients, SGD with momentum cannot be resumed exactly the same as the previous training process. 

I may have some misunderstandings on the code. Could you please have a look on this?

**Comment by antinucleon** [comment]
Right, without m_w is not exactly resumed, but our observation is m_w is not very important. Also, most of NAN is caused by extreme momentum, clear momentum will help. As @auroraxie suggests, deleted previous 10 round model before NAN appear will fix NAN problem in most of cases.
