### ISSUE TITLE
USE_CUDNN == 2 in cuDNN pooling layer

### ISSUE THREAD

**Issue by zhongwen** [dmlc/cxxnet#119]
I am just wondering whether [CXXNET_USE_CUDNN == 2](https://github.com/dmlc/cxxnet/blob/master/src/layer/cudnn_pooling_layer-inl.hpp#L24) in the cudnn_pooling layer is intended, or it should be corrected from 2 to 1? If it is intended, could you please explain a bit about this?

**Comment by antinucleon** [comment]
In some version of CUDNN, pooling is not stable so I use this way to disable it. I will test new CuDNN

**Comment by antinucleon** [comment]
I just fixed CuDNN pooling. And I added padding in CuDNN pooling.
