### ISSUE TITLE
Matlab wrapper , example example_conv train-error -nan

### ISSUE THREAD

**Issue by StevenLOL** [dmlc/cxxnet#122]
Build on 1st May 2015, under gcc-4.7 , MATLAB 2015 a, UBUNT 14.10

Both example and example_conv  gives -nan , is it an error?

>> example
	train-error:0.123883	eval-error:0.0704
	train-error:0.0598833	eval-error:0.0516
	train-error:*-nan*	eval-error:0.0704

ans =

	train-error:-nan	eval-error:0.0704

>> example_conv
	train-error:0.135717	eval-error:0.0213
	train-error:0.03135	eval-error:0.0191
	train-error:*-nan*	eval-error:0.0213
	train-error:0.0318833	eval-error:0.0154
	train-error:0.0245833	eval-error:0.0125
	train-error:0.0212833	eval-error:0.0113
	train-error:0.0199	eval-error:0.0117
	train-error:0.0177667	eval-error:0.0107
	train-error:0.01615	eval-error:0.0096
	train-error:0.0151	eval-error:0.0102
	train-error:0.0144667	eval-error:0.0097
	train-error:0.0133833	eval-error:0.01
	train-error:0.013	eval-error:0.0093
	train-error:0.0127667	eval-error:0.0088
	train-error:0.0118333	eval-error:0.0095
	train-error:0.01135	eval-error:0.0085
	train-error:0.0115667	eval-error:0.0082
	train-error:0.01115	eval-error:0.0086

**Comment by winstywang** [comment]
It is not an error. It is because we call evaluate twice after training one epoch.

**Comment by StevenLOL** [comment]
Thanks, would you like to explain why train the network in this way?
