### ISSUE TITLE
about dmlc-core and rabit

### ISSUE THREAD

**Issue by rongrongxiangxin** [dmlc/cxxnet#126]
one machine with multi-gpu, are the dmlc-core and rabit must for building cxxnet?

**Comment by winstywang** [comment]
We will migrate cxxnet to use some common components of dmlc, so dmlc-core is required currently. There is not third party dependency involved.
rabit is not required. You can disable it in the makefile.

**Comment by rongrongxiangxin** [comment]
There are some building errors in "./dmlc-core/include/dmlc/threadediter.h" and "src/io/iter_image_recordio-inl.hpp"

**Comment by winstywang** [comment]
Could you simply check your gcc and g++ version? 4.6 is minimum to build the project.

**Comment by rongrongxiangxin** [comment]
Oh, that's it. My gcc version is 4.4.7. Thanks.
