### ISSUE TITLE
python wrapper ctypes error

### ISSUE THREAD

**Issue by davutpolat** [dmlc/cxxnet#131]
Hi,

when i import cxxnet into my python script, it throw following error

OSError: path_to_cxxnet/cxxnet-master/wrapper/libcxxnetwrapper.so: undefined symbol: _ZN4dmlc19RecordIOChunkReaderC1ENS_10InputSplit4BlobEjj

i think there is some source is missing 

i can compile and run xgboost on my computer, i dont think it is environment problem

**Comment by tqchen** [comment]
@davutpolat  I have updated the Makefile, can you try again? Thanks

**Comment by davutpolat** [comment]
Still getting same error, here is the full text of error

    import cxxnet 
  File "/home/davut/Desktop/kaggle/cxxnet-master/wrapper/cxxnet.py", line 20, in <module>
    cxnlib = ctypes.cdll.LoadLibrary(CXXNET_PATH)
  File "/home/davut/anaconda3/lib/python3.4/ctypes/__init__.py", line 429, in LoadLibrary
    return self._dlltype(name)
  File "/home/davut/anaconda3/lib/python3.4/ctypes/__init__.py", line 351, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: /home/davut/Desktop/kaggle/cxxnet-master/wrapper/libcxxnetwrapper.so: undefined symbol: _ZN6cxxnet5layer11CreateLayerIN7mshadow3cpuEEEPNS0_6ILayerIT_EEiPNS2_6RandomIS5_fEEPKNS0_9LabelInfoE

**Comment by davutpolat** [comment]
My guess is, while linking shared object with its dependencies, a library  is missed,

**Comment by liueryun** [comment]
I got the same error message. I replaced line 15 and 17 in cxxnet.py with the following.
CXXNET_PATH = os.path.dirname(os.path.abspath(__file__)) + '/libcxxnetwrapper.so'

**Comment by davutpolat** [comment]
i tried your suggest, it did not help, got same error, it is not path problem, it is linking problem i guess

**Comment by tqchen** [comment]
Sorry about the delayed response. @davutpolat  there is a pull request fixing this issue have been merged, can you try again to see if the problem was fixed?

Thanks

**Comment by davutpolat** [comment]
it is fixed, Tianqi thank you very much, what was the problem ?

**Comment by tqchen** [comment]
There was some updates in the library dependency and we forget to update
the makefile to link all the deps.

Sorry about the problem

On Tue, May 12, 2015 at 12:28 PM, davutpolat <notifications@github.com>
wrote:

> it is fixed, Tianqi thank you very much, what was the problem ?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/dmlc/cxxnet/issues/131#issuecomment-101394057>.
>



-- 
Sincerely,
------------------------------------------------
Tianqi Chen
Computer Science & Engineering, University of Washington
