### ISSUE TITLE
compile error on windows7

### ISSUE THREAD

**Issue by wguo68** [dmlc/cxxnet#132]
where is dmlc/base.h and dmlc/logging.h ?

...1>d:\deeplearning\cxxnet\cxxnet-master\src\utils\utils.h(13): fatal error C1083: Cannot open include file: 'dmlc/base.h': No such file or directory

**Comment by antinucleon** [comment]
CXXNET is now depends on [dmlc-core](https://github.com/dmlc/dmlc-core) and [rabbit](https://github.com/dmlc/rabit). Because I don't have Windows machine, I didn't update the sln for a while.

**Comment by tqchen** [comment]
rabit dependency is option, but dmlc-core is a must now, You can checkout the dmlc-core library to build the newest version

**Comment by tqchen** [comment]
@wguo68  may I know updates on this? Did you manage to compile the windows version?

**Comment by wguo68** [comment]
I compiled the old version，but have no time to try it. I may compile the new version when I have time.

**Comment by wguo68** [comment]
I compile the new version of CXXNET. There are compile errors such as :
>d:\cxxnet\new\cxxnet-master\src\utils\./thread.h(36): error C2039: 'Assert' : is not a member of 'cxxnet::utils' (..\..\..\src\io\data.cpp)
...
1>..\..\..\src\io\data.cpp(46): error C2061: syntax error : identifier 'ImageRecordIOIterator'
1>..\..\..\src\io\data.cpp(46): error C2512: 'cxxnet::AugmentIterator' : no appropriate default constructor available

I then copy the code of "rabit::Util::Assert " to the namespace utils in thead.h.  The first error gone, but where is the definition for "ImageRecordIOIterator" ?
