### ISSUE TITLE
error C4996: 'fopen': This function or variable may be unsafe.

### ISSUE THREAD

**Issue by wguo68** [dmlc/cxxnet#133]
Although there is  _CRT_SECURE_NO_WARNINGS defined before any header in the utils.h ,the following error is still not fixed?

cxxnet-master\src\utils\utils.h(145): error C4996: 'fopen': This function or variable may be unsafe. Consider using fopen_s instead. To disable deprecation, use _CRT_SECURE_NO_WARNINGS. See online help for details.
2>          d:\program files (x86)\microsoft visual studio 12.0\vc\include\stdio.h(211) : see declaration of 'fopen

**Comment by tqchen** [comment]
Maybe it was missing in some cpp file can you check the cpp files in the project and see if some places miss the define?

**Comment by wguo68** [comment]
When I restart my computer several hours  later and rebuild the project again , the error disappeared.

**Comment by superzrx** [comment]
@wguo68 If you work with vs you can try define it at C/C++->pre process->pre process define. It may help
