### ISSUE TITLE
can not open file "./data/train-images-idx3-ubyte"  on windows7 ?

### ISSUE THREAD

**Issue by wguo68** [dmlc/cxxnet#135]
I like to test if the example mnist can work.  I download the mnist data from http://yann.lecun.com/exdb/mnist/ and extract these file to the data directory ,When I run the command :              
               ..\..\bin\cxxnet     .\MNIST.CONF
   the error says It can not  open file "./data/train-images-idx3-ubyte"?
   What's the problem? Is the unzipped file not correct? I use 7z to unzip these compressed files.

**Comment by wguo68** [comment]
I generated the  4 files in ubuntu as the instructions in run.sh :
      gzip -d  train-images-idx3-ubyte.gz
Then I copy these files to windows7 . Now it can run the MNIST example. 
 So "gzip -d " is not same as  unzip.

**Comment by tqchen** [comment]
Thanks

**Comment by Patrick213** [comment]
I downloaded the software 7z to gzip the 4 files, but it still cannot open the files.
Any other suggestions?
Thank you!

**Comment by abdullahbas** [comment]
I tried same ways but it still throws same error.  How can we solve this problem ?
