### ISSUE TITLE
Compile error on Ubuntu 12.04

### ISSUE THREAD

**Issue by lsy1993311** [dmlc/cxxnet#142]
When I compile cxxnet , I got  
src/config.cc:16:7: error: looser throw specifier for ‘virtual dmlc::TokenizeError::~TokenizeError()’
/usr/include/c++/4.6/exception:65:13: error:   overriding ‘virtual std::exception::~exception() throw ()’
make[1]: *** [config.o] Error 1
make[1]: Leaving directory `/home/liujingyu/cxxnet/dmlc-core'

Can anyone help me?

**Comment by winstywang** [comment]
Please make sure gcc/g++ version is greater than 4.6, and try it again
