### ISSUE TITLE
task fine-tuning failed

### ISSUE THREAD

**Issue by zhulinchao** [dmlc/cxxnet#147]
Hi,
I've been using cxxnet for a while, but I met a problem in the latest version.
I was trying to fine-tune a pre-trained model from Imagenet to my own dataset. However, I met floating point exception. I suspected that it was problematic when two conf files are different (but it has to be different for fine-tuning), so I applied a simple test on MNIST.
I set the task as fine-tune, and then set model_in as one of the models obtained from training `MNIST_CONV.conf`. 
In this case, I still met floating point exception.
Thank you in advance for your great help.

**Comment by antinucleon** [comment]
We are fixing it now. It will be done in late today.

**Comment by zhulinchao** [comment]
Thank you for you work, I just reorganizing my last issue to make it easier to understand. :)

**Comment by winstywang** [comment]
Fixed. Sorry for my insufficient test.
If you train a model using version before https://github.com/dmlc/cxxnet/commit/d32c38f9c69c6fcf689124679ef03c7e11e09e63, you need to rename all the pooling layers with suffix old (max_pooling -> max_pooling_old, avg_pooling -> avg_pooling_old), and you cannot use finetune on these models.
All functions are correct if you use version later than https://github.com/dmlc/cxxnet/commit/802e7f57066252e30f9e2cd30f7ac4a00e461f98 .

**Comment by winstywang** [comment]
Please feel free to try it, if you find other issues, please let me know.

**Comment by winstywang** [comment]
Use another simpler way to fix it. All the old models can be used for finetune.
