### ISSUE TITLE
extra_data@iter_attach_txt-inl.hpp usage

### ISSUE THREAD

**Issue by xiw9** [dmlc/cxxnet#148]
Hi,
I'm implementing some RNN layers based on this framework.
Does the framework allow a layer getting extra data directly from files?
The RNN layers need a sequence indicator to tell it the beginning of a sequence.
I found a variable called "extra_data" in "iter_attach_txt-inl.hpp", can it be used in this task?
A short example would be appreciated: )
Thanks.

**Comment by antinucleon** [comment]
I am trying to finishing RNN is recent days. You may check this branch:https://github.com/antinucleon/cxxnet/tree/lstm2

**Comment by xiw9** [comment]
Thanks,
BTW, my implementation: https://github.com/xiw9/cxxnet/blob/master/src/layer/lstm_layer-inl.hpp
It unrolls the recurrent part. Batch BPTT is also ready.
The sequence indicator in training process is done by using an additional label.
But it fails in testing. :(

**Comment by xiw9** [comment]
solved,  https://github.com/dmlc/cxxnet/pull/159
