### ISSUE TITLE
About The Multi-label Training

### ISSUE THREAD

**Issue by zhangchen-qinyinghua** [dmlc/cxxnet#160]
Hi,

This is maybe just insignificant "Bug", about the Multi-label Training (and the document).

As the document said (https://github.com/dmlc/cxxnet/blob/master/doc/advanced.md)"
label_vec[1, 5) = bounding_box
"

But when I did so, I got error.

So I checked the code, and found that the solution is just remove a space between 1 and 5, as below,
label_vec[1,5) = bounding_box

This kind of fragile caused by the code in nnet_config.h ,
which reads,

sscanf(name, "label_vec[%u,%u)", &a, &b) == 2

**Comment by winstywang** [comment]
Thanks for the report. I will fix it at next update of docs.

**Comment by winstywang** [comment]
Fixed now.

**Comment by zhangchen-qinyinghua** [comment]
Thank u for your work!

I noticed that new version of cxxnet gains a lot more new good functions~
