### ISSUE TITLE
./build.sh failed!

### ISSUE THREAD

**Issue by andyyuan78** [dmlc/cxxnet#162]
ubgpu@ubgpu:~/github/DMLC/cxxnet$ sudo ./build.sh 
[sudo] password for ubgpu: 
g++ -DMSHADOW_FORCE_STREAM -Wall -g -O3 -I./mshadow/ -I./dmlc-core/include -fPIC -msse3 -funroll-loops -Wno-unused-parameter -Wno-unknown-pragmas -I/usr/local/cuda/include -DMSHADOW_USE_CBLAS=1 -DMSHADOW_USE_MKL=0 -DMSHADOW_RABIT_PS=0 -DMSHADOW_DIST_PS=0 -DCXXNET_USE_OPENCV=0 -DCXXNET_USE_OPENCV_DECODER=0 -fopenmp   -o bin/cxxnet src/local_main.cpp layer_cpu.o updater_cpu.o nnet_cpu.o main.o nnet_ps_server.o data.o dmlc-core/libdmlc.a layer_gpu.o updater_gpu.o nnet_gpu.o -pthread -lm -lcudart -lcublas -lcurand -L/usr/local/cuda/lib64 -lrt           -ljpeg
layer_cpu.o: In function `mshadow::expr::BLASEngine<mshadow::cpu>::gemm(bool, bool, int, int, int, float, float const*, int, float const*, int, float, float*, int)':
/home/ubgpu/github/DMLC/cxxnet/./mshadow/mshadow/././dot_engine-inl.h:38: undefined reference to `cblas_sgemm'
/home/ubgpu/github/DMLC/cxxnet/./mshadow/mshadow/././dot_engine-inl.h:38: undefined reference to `cblas_sgemm'
/home/ubgpu/github/DMLC/cxxnet/./mshadow/mshadow/././dot_engine-inl.h:38: undefined reference to `cblas_sgemm'
/home/ubgpu/github/DMLC/cxxnet/./mshadow/mshadow/././dot_engine-inl.h:38: undefined reference to `cblas_sgemm'
/home/ubgpu/github/DMLC/cxxnet/./mshadow/mshadow/././dot_engine-inl.h:38: undefined reference to `cblas_sgemm'
layer_cpu.o:/home/ubgpu/github/DMLC/cxxnet/./mshadow/mshadow/././dot_engine-inl.h:38: more undefined references to `cblas_sgemm' follow
collect2: error: ld returned 1 exit status
make: *** [bin/cxxnet] Error 1
ubgpu@ubgpu:~/github/DMLC/cxxnet$

**Comment by antinucleon** [comment]
Check your blas setting, eg, copy ```make/config.mk``` to ```./```, then change blas setting. Ref: https://github.com/dmlc/cxxnet#build

**Comment by andyyuan78** [comment]
it works!
