### ISSUE TITLE
./build_ps.sh  failed

### ISSUE THREAD

**Issue by ericustc** [dmlc/cxxnet#164]
/root/parallel/cxxnet/ps-lite/src/system/customer.h:54: undefined reference to `ps::Manager::RemoveCustomer(int)'
/root/parallel/cxxnet/ps-lite/src/system/customer.h:53: undefined reference to `ps::Executor::~Executor()'
nnet_cpu.o: In function `~Customer':
/root/parallel/cxxnet/ps-lite/src/system/customer.h:54: undefined reference to `ps::Manager::RemoveCustomer(int)'
/root/parallel/cxxnet/ps-lite/src/system/customer.h:53: undefined reference to `ps::Executor::~Executor()'
/root/parallel/cxxnet/ps-lite/src/system/customer.h:54: undefined reference to `ps::Manager::RemoveCustomer(int)'
nnet_cpu.o: In function `~Parameter':
/root/parallel/cxxnet/ps-lite/src/system/customer.h:53: undefined reference to `ps::Executor::~Executor()'
nnet_cpu.o: In function `~Customer':
/root/parallel/cxxnet/ps-lite/src/system/customer.h:54: undefined reference to `ps::Manager::RemoveCustomer(int)'
/root/parallel/cxxnet/ps-lite/src/system/customer.h:53: undefined reference to `ps::Executor::~Executor()'
/root/parallel/cxxnet/ps-lite/src/system/customer.h:54: undefined reference to `ps::Manager::RemoveCustomer(int)'
/root/parallel/cxxnet/ps-lite/src/system/customer.h:53: undefined reference to `ps::Executor::~Executor()'
/root/parallel/cxxnet/ps-lite/src/system/customer.h:54: undefined reference to `ps::Manager::RemoveCustomer(int)'
/root/parallel/cxxnet/ps-lite/src/system/customer.h:53: undefined reference to `ps::Executor::~Executor()'
nnet_cpu.o: In function `NextCustomerID':
/root/parallel/cxxnet/ps-lite/src/ps.h:315: undefined reference to `ps::Manager::NextCustomerID()'
nnet_cpu.o: In function `Customer':
/root/parallel/cxxnet/ps-lite/src/system/customer.h:50: undefined reference to `ps::Executor::Executor(ps::Customer&)'
/root/parallel/cxxnet/ps-lite/src/system/customer.h:51: undefined reference to `ps::Manager::AddCustomer(ps::Customer*)'
nnet_cpu.o: In function `ps::Postoffice::instance()':
/root/parallel/cxxnet/ps-lite/src/system/postoffice.h:11: undefined reference to `ps::Postoffice::Postoffice()'
/root/parallel/cxxnet/ps-lite/src/system/postoffice.h:11: undefined reference to `ps::Postoffice::~Postoffice()'
/root/parallel/cxxnet/ps-lite/src/system/postoffice.h:11: undefined reference to `ps::Postoffice::Postoffice()'
/root/parallel/cxxnet/ps-lite/src/system/postoffice.h:11: undefined reference to `ps::Postoffice::~Postoffice()'
nnet_cpu.o: In function `Customer':
/root/parallel/cxxnet/ps-lite/src/system/customer.h:50: undefined reference to `ps::Executor::~Executor()'
nnet_cpu.o: In function `~Parameter':
/root/parallel/cxxnet/ps-lite/src/parameter/parameter.h:10: undefined reference to `vtable for ps::Parameter'
nnet_cpu.o: In function `ps::Task::add_value_type(ps::DataType)':
/root/parallel/cxxnet/ps-lite/src/proto/task.pb.h:760: undefined reference to `ps::DataType_IsValid(int)'
nnet_cpu.o: In function `ps::Task::key_range() const':
/root/parallel/cxxnet/ps-lite/src/proto/task.pb.h:630: undefined reference to `ps::Task::default_instance_'
/root/parallel/cxxnet/ps-lite/src/proto/task.pb.h:630: undefined reference to `ps::Task::default_instance_'
/root/parallel/cxxnet/ps-lite/src/proto/task.pb.h:630: undefined reference to `ps::Task::default_instance_'
nnet_cpu.o: In function `ps::Task::mutable_key_range()':
/root/parallel/cxxnet/ps-lite/src/proto/task.pb.h:634: undefined reference to `ps::PbRange::PbRange()'
/root/parallel/cxxnet/ps-lite/src/proto/task.pb.h:634: undefined reference to `ps::PbRange::PbRange()'
/root/parallel/cxxnet/ps-lite/src/proto/task.pb.h:634: undefined reference to `ps::PbRange::PbRange()'
nnet_cpu.o: In function `ps::Task::key_range() const':
/root/parallel/cxxnet/ps-lite/src/proto/task.pb.h:630: undefined reference to `ps::Task::default_instance_'
nnet_cpu.o: In function `ps::Task::mutable_key_range()':
/root/parallel/cxxnet/ps-lite/src/proto/task.pb.h:634: undefined reference to `ps::PbRange::PbRange()'
nnet_cpu.o: In function `ps::Task::key_range() const':
/root/parallel/cxxnet/ps-lite/src/proto/task.pb.h:630: undefined reference to `ps::Task::default_instance_'
nnet_cpu.o: In function `ps::Parameter::Request(int, int, std::initializer_list<int> const&, google::protobuf::RepeatedPtrField<ps::Filter> const&, ps::Range<unsigned long long> const&)':
/root/parallel/cxxnet/ps-lite/src/parameter/parameter.h:30: undefined reference to `ps::Task::Task()'
nnet_cpu.o: In function `google::protobuf::internal::GenericTypeHandler<ps::Filter>::New()':
/root/parallel/cxxnet/ps-lite/third_party/include/google/protobuf/repeated_field.h:335: undefined reference to `ps::Filter::Filter()'
nnet_cpu.o: In function `ps::Parameter::Request(int, int, std::initializer_list<int> const&, google::protobuf::RepeatedPtrField<ps::Filter> const&, ps::Range<unsigned long long> const&)':
/root/parallel/cxxnet/ps-lite/src/parameter/parameter.h:34: undefined reference to `ps::Filter::CopyFrom(ps::Filter const&)'
nnet_cpu.o: In function `google::protobuf::internal::GenericTypeHandler<ps::Filter>::New()':
/root/parallel/cxxnet/ps-lite/third_party/include/google/protobuf/repeated_field.h:335: undefined reference to `ps::Filter::Filter()'
nnet_cpu.o: In function `ps::Parameter::Request(int, int, std::initializer_list<int> const&, google::protobuf::RepeatedPtrField<ps::Filter> const&, ps::Range<unsigned long long> const&)':
/root/parallel/cxxnet/ps-lite/src/parameter/parameter.h:34: undefined reference to `ps::Filter::CopyFrom(ps::Filter const&)'
nnet_cpu.o: In function `google::protobuf::internal::GenericTypeHandler<ps::Filter>::New()':
/root/parallel/cxxnet/ps-lite/third_party/include/google/protobuf/repeated_field.h:335: undefined reference to `ps::Filter::Filter()'
nnet_cpu.o: In function `ps::Parameter::Request(int, int, std::initializer_list<int> const&, google::protobuf::RepeatedPtrField<ps::Filter> const&, ps::Range<unsigned long long> const&)':
/root/parallel/cxxnet/ps-lite/src/parameter/parameter.h:34: undefined reference to `ps::Filter::CopyFrom(ps::Filter const&)'
nnet_cpu.o: In function `google::protobuf::internal::GenericTypeHandler<ps::Filter>::New()':
/root/parallel/cxxnet/ps-lite/third_party/include/google/protobuf/repeated_field.h:335: undefined reference to `ps::Filter::Filter()'
nnet_cpu.o: In function `ps::Parameter::Request(int, int, std::initializer_list<int> const&, google::protobuf::RepeatedPtrField<ps::Filter> const&, ps::Range<unsigned long long> const&)':
/root/parallel/cxxnet/ps-lite/src/parameter/parameter.h:34: undefined reference to `ps::Filter::CopyFrom(ps::Filter const&)'
nnet_cpu.o: In function `ps::Task::mutable_key_range()':
/root/parallel/cxxnet/ps-lite/src/proto/task.pb.h:634: undefined reference to `ps::PbRange::PbRange()'
nnet_cpu.o: In function `ps::Parameter::Request(int, int, std::initializer_list<int> const&, google::protobuf::RepeatedPtrField<ps::Filter> const&, ps::Range<unsigned long long> const&)':
/root/parallel/cxxnet/ps-lite/src/proto/task.pb.h:634: undefined reference to `ps::Task::~Task()'
nnet_cpu.o: In function `ps::Message::~Message()':
/root/parallel/cxxnet/ps-lite/src/system/message.h:10: undefined reference to `ps::Task::~Task()'
nnet_cpu.o: In function `Message':
/root/parallel/cxxnet/ps-lite/src/system/message.h:14: undefined reference to `ps::Task::Task(ps::Task const&)'
nnet_cpu.o: In function `ps::Customer::Submit(ps::Message*)':
/root/parallel/cxxnet/ps-lite/src/system/customer.h:93: undefined reference to `ps::Executor::Submit(ps::Message*)'
nnet_cpu.o: In function `~Message':
/root/parallel/cxxnet/ps-lite/src/system/message.h:10: undefined reference to `ps::Task::~Task()'
nnet_cpu.o: In function `ps::Task::mutable_key_range()':
/root/parallel/cxxnet/ps-lite/src/proto/task.pb.h:634: undefined reference to `ps::PbRange::PbRange()'
nnet_cpu.o: In function `ps::Task::mutable_param()':
/root/parallel/cxxnet/ps-lite/src/proto/task.pb.h:971: undefined reference to `ps::ParamCall::ParamCall()'
nnet_cpu.o: In function `Message':
/root/parallel/cxxnet/ps-lite/src/system/message.h:14: undefined reference to `ps::Task::~Task()'
nnet_cpu.o: In function `mshadow::ps::DistModel<mshadow::cpu, float>::ServerInitKey(mshadow::Tensor<mshadow::cpu, 2, float>, int)':
/root/parallel/cxxnet/mshadow/mshadow-ps/./ps_dist-inl.h:67: undefined reference to `ps::Task::~Task()'
/root/parallel/cxxnet/mshadow/mshadow-ps/./ps_dist-inl.h:67: undefined reference to `ps::Task::~Task()'
nnet_cpu.o: In function `Message':
/root/parallel/cxxnet/ps-lite/src/system/message.h:14: undefined reference to `ps::Task::Task(ps::Task const&)'
nnet_cpu.o: In function `ps::Customer::Submit(ps::Message*)':
/root/parallel/cxxnet/ps-lite/src/system/customer.h:93: undefined reference to `ps::Executor::Submit(ps::Message*)'
nnet_cpu.o: In function `~Message':
/root/parallel/cxxnet/ps-lite/src/system/message.h:10: undefined reference to `ps::Task::~Task()'
nnet_cpu.o: In function `mshadow::ps::DistModel<mshadow::cpu, float>::HandlePushFinish(mshadow::Tensor<mshadow::cpu, 3, float>, int)':
/root/parallel/cxxnet/mshadow/mshadow-ps/./ps_dist-inl.h:85: undefined reference to `ps::Task::~Task()'
/root/parallel/cxxnet/mshadow/mshadow-ps/./ps_dist-inl.h:88: undefined reference to `ps::Task::~Task()'
nnet_cpu.o: In function `ps::Task::mutable_param()':
/root/parallel/cxxnet/ps-lite/src/proto/task.pb.h:971: undefined reference to `ps::ParamCall::ParamCall()'
nnet_cpu.o: In function `ps::Task::mutable_key_range()':
/root/parallel/cxxnet/ps-lite/src/proto/task.pb.h:634: undefined reference to `ps::PbRange::PbRange()'
nnet_cpu.o: In function `mshadow::ps::DistModel<mshadow::cpu, float>::HandlePushFinish(mshadow::Tensor<mshadow::cpu, 3, float>, int)':
/root/parallel/cxxnet/mshadow/mshadow-ps/./ps_dist-inl.h:85: undefined reference to `ps::Task::~Task()'
/root/parallel/cxxnet/mshadow/mshadow-ps/./ps_dist-inl.h:88: undefined reference to `ps::Task::~Task()'
nnet_cpu.o: In function `Message':
/root/parallel/cxxnet/ps-lite/src/system/message.h:14: undefined reference to `ps::Task::~Task()'
nnet_cpu.o: In function `MyNode':
/root/parallel/cxxnet/ps-lite/src/ps.h:299: undefined reference to `ps::Node::Node(ps::Node const&)'
nnet_cpu.o: In function `IsWorkerNode':
/root/parallel/cxxnet/ps-lite/src/ps.h:303: undefined reference to `ps::Node::~Node()'
nnet_cpu.o: In function `MyNode':
/root/parallel/cxxnet/ps-lite/src/ps.h:299: undefined reference to `ps::Node::Node(ps::Node const&)'
nnet_cpu.o: In function `IsServerNode':
/root/parallel/cxxnet/ps-lite/src/ps.h:305: undefined reference to `ps::Node::~Node()'
nnet_cpu.o: In function `ps::Postoffice::instance()':
/root/parallel/cxxnet/ps-lite/src/system/postoffice.h:11: undefined reference to `ps::Postoffice::Postoffice()'
/root/parallel/cxxnet/ps-lite/src/system/postoffice.h:11: undefined reference to `ps::Postoffice::~Postoffice()'
/root/parallel/cxxnet/ps-lite/src/system/postoffice.h:11: undefined reference to `ps::Postoffice::Postoffice()'
/root/parallel/cxxnet/ps-lite/src/system/postoffice.h:11: undefined reference to `ps::Postoffice::~Postoffice()'
nnet_cpu.o: In function `ps::Task::key_range() const':
/root/parallel/cxxnet/ps-lite/src/proto/task.pb.h:630: undefined reference to `ps::Task::default_instance_'
nnet_cpu.o: In function `cxxnet::nnet::CXXNetThreadTrainer<mshadow::cpu>::SetParam(char const*, char const*)':
/root/parallel/cxxnet/src/nnet/nnet_impl-inl.hpp:59: undefined reference to `ps::fLB::FLAGS_local'
nnet_cpu.o: In function `MyNode':
/root/parallel/cxxnet/ps-lite/src/ps.h:299: undefined reference to `ps::Node::Node(ps::Node const&)'
nnet_cpu.o: In function `IsWorkerNode':
/root/parallel/cxxnet/ps-lite/src/ps.h:303: undefined reference to `ps::Node::~Node()'
nnet_cpu.o: In function `MyNode':
/root/parallel/cxxnet/ps-lite/src/ps.h:299: undefined reference to `ps::Node::Node(ps::Node const&)'
nnet_cpu.o: In function `IsWorkerNode':
/root/parallel/cxxnet/ps-lite/src/ps.h:303: undefined reference to `ps::Node::~Node()'
nnet_cpu.o: In function `MyNode':
/root/parallel/cxxnet/ps-lite/src/ps.h:299: undefined reference to `ps::Node::Node(ps::Node const&)'
nnet_cpu.o: In function `MyRank':
/root/parallel/cxxnet/ps-lite/src/ps.h:321: undefined reference to `ps::Node::~Node()'
nnet_cpu.o: In function `ps::Postoffice::instance()':
/root/parallel/cxxnet/ps-lite/src/system/postoffice.h:11: undefined reference to `ps::Postoffice::Postoffice()'
/root/parallel/cxxnet/ps-lite/src/system/postoffice.h:11: undefined reference to `ps::Postoffice::~Postoffice()'
nnet_cpu.o: In function `MyNode':
/root/parallel/cxxnet/ps-lite/src/ps.h:299: undefined reference to `ps::Node::Node(ps::Node const&)'
nnet_cpu.o: In function `IsServerNode':
/root/parallel/cxxnet/ps-lite/src/ps.h:305: undefined reference to `ps::Node::~Node()'
nnet_cpu.o: In function `ps::Postoffice::instance()':
/root/parallel/cxxnet/ps-lite/src/system/postoffice.h:11: undefined reference to `ps::Postoffice::Postoffice()'
/root/parallel/cxxnet/ps-lite/src/system/postoffice.h:11: undefined reference to `ps::Postoffice::~Postoffice()'
/root/parallel/cxxnet/ps-lite/src/system/postoffice.h:11: undefined reference to `ps::Postoffice::Postoffice()'
/root/parallel/cxxnet/ps-lite/src/system/postoffice.h:11: undefined reference to `ps::Postoffice::~Postoffice()'
nnet_cpu.o: In function `MyNode':
/root/parallel/cxxnet/ps-lite/src/ps.h:299: undefined reference to `ps::Node::Node(ps::Node const&)'
nnet_cpu.o: In function `IsServerNode':
/root/parallel/cxxnet/ps-lite/src/ps.h:305: undefined reference to `ps::Node::~Node()'
nnet_cpu.o: In function `ps::Postoffice::instance()':
/root/parallel/cxxnet/ps-lite/src/system/postoffice.h:11: undefined reference to `ps::Postoffice::Postoffice()'
/root/parallel/cxxnet/ps-lite/src/system/postoffice.h:11: undefined reference to `ps::Postoffice::~Postoffice()'
/root/parallel/cxxnet/ps-lite/src/system/postoffice.h:11: undefined reference to `ps::Postoffice::Postoffice()'
/root/parallel/cxxnet/ps-lite/src/system/postoffice.h:11: undefined reference to `ps::Postoffice::~Postoffice()'
/root/parallel/cxxnet/ps-lite/src/system/postoffice.h:11: undefined reference to `ps::Postoffice::Postoffice()'
/root/parallel/cxxnet/ps-lite/src/system/postoffice.h:11: undefined reference to `ps::Postoffice::~Postoffice()'
/root/parallel/cxxnet/ps-lite/src/system/postoffice.h:11: undefined reference to `ps::Postoffice::Postoffice()'
/root/parallel/cxxnet/ps-lite/src/system/postoffice.h:11: undefined reference to `ps::Postoffice::~Postoffice()'
nnet_cpu.o:(.data.rel.ro._ZTIN2ps7KVLayerIfN7mshadow2ps14UpdaterWrapperIfEEEE[_ZTIN2ps7KVLayerIfN7mshadow2ps14UpdaterWrapperIfEEEE]+0x10): undefined reference to `typeinfo for ps::Parameter'
nnet_cpu.o:(.data.rel.ro._ZTVN2ps7KVLayerIfN7mshadow2ps14UpdaterWrapperIfEEEE[_ZTVN2ps7KVLayerIfN7mshadow2ps14UpdaterWrapperIfEEEE]+0x28): undefined reference to `ps::Parameter::ProcessRequest(ps::Message*)'
nnet_cpu.o:(.data.rel.ro._ZTVN2ps7KVLayerIfN7mshadow2ps14UpdaterWrapperIfEEEE[_ZTVN2ps7KVLayerIfN7mshadow2ps14UpdaterWrapperIfEEEE]+0x30): undefined reference to `ps::Parameter::ProcessResponse(ps::Message*)'
main.o: In function `MyNode':
/root/parallel/cxxnet/ps-lite/src/ps.h:299: undefined reference to `ps::Node::Node(ps::Node const&)'
main.o: In function `MyRank':
/root/parallel/cxxnet/ps-lite/src/ps.h:321: undefined reference to `ps::Node::~Node()'
main.o: In function `ps::Postoffice::instance()':
/root/parallel/cxxnet/ps-lite/src/system/postoffice.h:11: undefined reference to `ps::Postoffice::Postoffice()'
/root/parallel/cxxnet/ps-lite/src/system/postoffice.h:11: undefined reference to `ps::Postoffice::~Postoffice()'
nnet_ps_server.o: In function `MyNode':
/root/parallel/cxxnet/ps-lite/src/ps.h:299: undefined reference to `ps::Node::Node(ps::Node const&)'
nnet_ps_server.o: In function `MyRank':
/root/parallel/cxxnet/ps-lite/src/ps.h:321: undefined reference to `ps::Node::~Node()'
nnet_ps_server.o: In function `NextCustomerID':
/root/parallel/cxxnet/ps-lite/src/ps.h:315: undefined reference to `ps::Manager::NextCustomerID()'
nnet_ps_server.o: In function `Customer':
/root/parallel/cxxnet/ps-lite/src/system/customer.h:50: undefined reference to `ps::Executor::Executor(ps::Customer&)'
/root/parallel/cxxnet/ps-lite/src/system/customer.h:51: undefined reference to `ps::Manager::AddCustomer(ps::Customer*)'
nnet_ps_server.o: In function `MShadowServerNode':
/root/parallel/cxxnet/mshadow/mshadow-ps/./ps_dist-inl.h:113: undefined reference to `ps::Manager::TransferCustomer(ps::Customer*)'
nnet_ps_server.o: In function `ps::Postoffice::instance()':
/root/parallel/cxxnet/ps-lite/src/system/postoffice.h:11: undefined reference to `ps::Postoffice::Postoffice()'
/root/parallel/cxxnet/ps-lite/src/system/postoffice.h:11: undefined reference to `ps::Postoffice::~Postoffice()'
/root/parallel/cxxnet/ps-lite/src/system/postoffice.h:11: undefined reference to `ps::Postoffice::Postoffice()'
/root/parallel/cxxnet/ps-lite/src/system/postoffice.h:11: undefined reference to `ps::Postoffice::~Postoffice()'
/root/parallel/cxxnet/ps-lite/src/system/postoffice.h:11: undefined reference to `ps::Postoffice::Postoffice()'
/root/parallel/cxxnet/ps-lite/src/system/postoffice.h:11: undefined reference to `ps::Postoffice::~Postoffice()'
/root/parallel/cxxnet/ps-lite/src/system/postoffice.h:11: undefined reference to `ps::Postoffice::Postoffice()'
/root/parallel/cxxnet/ps-lite/src/system/postoffice.h:11: undefined reference to `ps::Postoffice::~Postoffice()'
nnet_ps_server.o: In function `~Parameter':
/root/parallel/cxxnet/ps-lite/src/parameter/parameter.h:10: undefined reference to `vtable for ps::Parameter'
nnet_ps_server.o: In function `Customer':
/root/parallel/cxxnet/ps-lite/src/system/customer.h:50: undefined reference to `ps::Executor::~Executor()'
data.o: In function `ps::Postoffice::instance()':
/root/parallel/cxxnet/ps-lite/src/system/postoffice.h:11: undefined reference to `ps::Postoffice::Postoffice()'
/root/parallel/cxxnet/ps-lite/src/system/postoffice.h:11: undefined reference to `ps::Postoffice::~Postoffice()'
data.o: In function `MyNode':
/root/parallel/cxxnet/ps-lite/src/ps.h:299: undefined reference to `ps::Node::Node(ps::Node const&)'
data.o: In function `IsWorkerNode':
/root/parallel/cxxnet/ps-lite/src/ps.h:303: undefined reference to `ps::Node::~Node()'
data.o: In function `MyNode':
/root/parallel/cxxnet/ps-lite/src/ps.h:299: undefined reference to `ps::Node::Node(ps::Node const&)'
data.o: In function `MyRank':
/root/parallel/cxxnet/ps-lite/src/ps.h:321: undefined reference to `ps::Node::~Node()'
data.o: In function `MyNode':
/root/parallel/cxxnet/ps-lite/src/ps.h:299: undefined reference to `ps::Node::Node(ps::Node const&)'
data.o: In function `IsServerNode':
/root/parallel/cxxnet/ps-lite/src/ps.h:305: undefined reference to `ps::Node::~Node()'
collect2: error: ld returned 1 exit status
make: *** [bin/cxxnet] Error 1
make: *** Waiting for unfinished jobs....

**Comment by viktor-ferenczi** [comment]
Same on Ubuntu 15.04 while using gcc 4.8.4

**Comment by mli** [comment]
will fix it in some minutes.

**Comment by mli** [comment]
i just missed to add $(PS_LDFLAGS) in the makefile. please have a pull and recompile

**Comment by ericustc** [comment]
It works
