### ISSUE TITLE
Predictions are only written in multiples of the batch size

### ISSUE THREAD

**Issue by jfkingiii** [dmlc/cxxnet#17]
The batch size in the pred.conf file included with the kaggle competition is 100; this does not cause an issue when scoring the kaggle test set since that has 130400 observations. However I found that when predicting on another dataset which has 9051 observations the output was truncated at 9000 records. I was able to correct this by setting batch size to 1. 

This behavior is a little unintuitive; you may want to consider scoring the fractional batch as well when the task is set to predict.

**Comment by antinucleon** [comment]
Fixed in current version.
