### ISSUE TITLE
Build error: glog/logging.h: No such file or directory

### ISSUE THREAD

**Issue by viktor-ferenczi** [dmlc/cxxnet#171]
Build error on Ubuntu 15.05, while trying to build with ```build_ps.sh``` (parameter server build):

Revision: 2dd95df6cfd32a4017143b24cab05d2a02aaa47e 

Build error: glog/logging.h: No such file or directory

Full output and build config:
https://gist.github.com/viktor-ferenczi/4f80b32eaafa20944327

**Comment by dkyang** [comment]
Have you installed glog? It seems that the include path of glog have't been added to config file correctly.

**Comment by zhongwen** [comment]
It should be fixed now. Please pull the latest version.

**Comment by viktor-ferenczi** [comment]
Works
