### ISSUE TITLE
Is gated conv. layer implemented in cxxnet?

### ISSUE THREAD

**Issue by yuzcccc** [dmlc/cxxnet#178]
When I say gated conv. layer, I mean the conv. layer that does not have activations (so as the gradients) when input feature within a conv. kernel is all-zero, which is proposed in the paper "Convolutional Neural Network Architectures for Matching Natural Language Sentences"

**Comment by antinucleon** [comment]
Sorry currently we don't have extra hand to write non-standard layer.
