### ISSUE TITLE
Really does exist such disadvantages of CXXNET?

### ISSUE THREAD

**Issue by Temmplar** [dmlc/cxxnet#180]
On Kaggle forum I have red:

The code base of cxxnet is indeed much smaller and simpler, but it comes at a price. For example it lacks scripting integration. Caffe has full support for high level scripting in Python, which makes tricks like network surgery possible. This is a great way of evolving your network architecture without completely losing your past training effort. It also allows for visualizing the internals of your neural network, which makes so much easier to debug and understand it.

I will really struggle from such disadvantages or it is possible to work out these some way? :)

**Comment by antinucleon** [comment]
We have python interface. It will be more friendly, somehow similar to keras soon
