### ISSUE TITLE
How to build im2bin?

### ISSUE THREAD

**Issue by zhzhanp** [dmlc/cxxnet#184]
I just download the latest code and build successfully. However, I cannot find the built im2bin. Instead, I found im2rec and bin2rec. I try to build im2bin with the makefile in /tools but found difficulties. Is im2bin not supported now? Or how to use im2rec? Which data iterator? Thanks.

**Comment by zhzhanp** [comment]
Now I use im2rec with the data iterator "imgrec". It really runs much faster than "img".

**Comment by winstywang** [comment]
I have just updated the im2rec related doc :) Welcome to check them.
