### ISSUE TITLE
how to iterate the image recordio file created by im2rec in cxxnet

### ISSUE THREAD

**Issue by tfwu** [dmlc/cxxnet#186]
Dear All, 

Given an image recordio file created by im2rec,  how can i read and iterate through all the image instances in the file?

I tried to use ImageRecordIOIterator directly, but got a lot compiling errors. 

I also tried to use the cxxnet::CreateIterator with the cfg filledin, but still have issues to get the image data. 

Examples are welcome and greatly appreciated. 

More generally,  it will be great if someone can write a brief intro. for the data manipulation in the cxxnet. 

thank you in advance

**Comment by winstywang** [comment]
What kinds of issues do you meet? Are you successful in training network using imgrec iterator?

**Comment by tfwu** [comment]
Hi, naiyang, 

thank you for the quick reply. 

It's not an issue in training.  

I just want to play with code so i can modify it towards my research. 

E.g., 

        std::string recFile = argv[1]; // precomputed rec file by im2rec
	std::string shape = argv[2];  // the data shape
	
	std::vector < std::pair<std::string, std::string> > cfg;
	cfg.push_back(std::make_pair("iter", "imgrec"));

	cxxnet::IIterator < cxxnet::DataBatch > *iter = cxxnet::CreateIterator(cfg);

	iter->SetParam("image_rec", recFile.c_str());
	iter->SetParam("input_shape", shape.c_str());
	iter->SetParam("batch_size", "100");

	iter->Init();
	iter->BeforeFirst();
	CHECK(iter->Next()) << "input image recordio failed";

	const cxxnet::DataBatch &batch(iter->Value());  // i can not get data from batch correctly. 

thank you.
