### ISSUE TITLE
Missing Code-Interface

### ISSUE THREAD

**Issue by crohkohl** [dmlc/cxxnet#193]
Hi,

thanks for your great library. I really like it. I think the library could greatly benefit from not only targeting static "offline" users that are going to use the compiled cxxnet program. Many developers (including me) require more a "library" style that can be easily included into an existing environment.

Simple scenarios are:
- On the fly image generation and custom image format
- Easy supply of extra data
- Integration into other libraries or applications, e.g. for predicting image patches and displaying a result to the user.
- simple prediction for single samples

A design proposal could be to rewrite the CXXNetLearnTask class into a higher level class that can be easily used and configured from external code. The cxxnet_main.cpp should then use that interface.

Good examples are in my opinion OpenCV or the CImg-library for providing a good "developer" experience.

What do you think?

**Comment by tqchen** [comment]
@crohkohl  sorry for the delayed reply. Thanks for being interested in our library. I totally agree with what you said. Actually, the cxxnet team is pushing a joint new effort on [mxnet](https://github.com/dmlc/mxnet), which should achieve what you said and beyond.
