### ISSUE TITLE
unknown iterator type imgbin of example kaggle bowl

### ISSUE THREAD

**Issue by OutOfMemory14** [dmlc/cxxnet#215]
When I try example of kaggle bowl, I got this error: "unknown iterator type imgbin", I also tried imgrec, but still can not figure it out.

**Comment by antinucleon** [comment]
Sorry im2bin is discarded. Please use new im2rec tools. Basically it is similar to im2bin in function, but with better performance.

**Comment by OutOfMemory14** [comment]
Thanks a lot.
