### ISSUE TITLE
Layer model issues

### ISSUE THREAD

**Issue by DrustZ** [dmlc/cxxnet#216]
@antinucleon @tqchen @winstywang 
I noted the layer will save and load the model from ``IStream``
For example , the convolution layer, will load ``param_`` and ``wmat_`` , ``bias_``from the ``IStream``.
Now I want to add more ``TensorContianer`` to a layer, can I simply apply ``addedTensor.SaveBinary`` and ``addedTensor.LoadBinary`` to the function?

**Comment by antinucleon** [comment]
I don't recommend to do in this way, but it is possible.
