### ISSUE TITLE
What are the steps to add a new layer in cxxnet?

### ISSUE THREAD

**Issue by OutOfMemory14** [dmlc/cxxnet#220]
I am a newer to cxxnet, and I want to add a new self-defined layer, what steps should I take?

**Comment by superzrx** [comment]
@OutOfMemory14 
1.  Find a layer with the most similar function.
2.  Try to build your own layer based on it.
2.x For some complex case you need to define your own mshadow Exp like in insanity_pooling_layer-inl.hpp.
3.  Test and modify layer.h/layer_impl-inl.hpp

may it helps :)

**Comment by OutOfMemory14** [comment]
@superzrx  Thanks a lot! But when I try to implement a new layer, I faced the problem that “nodes_in” is of 4 dimension, but my data is 5 dims, looks like this (index, topLeftX, topLeftY, downRightX, downRightY  ). Now, I have no idea how to deal with it.

**Comment by OutOfMemory14** [comment]
Thanks a lot!
