### ISSUE TITLE
Configure question about activtionlayer and split layer 

### ISSUE THREAD

**Issue by junranhe** [dmlc/cxxnet#233]
activetionlayer can I config  it self loop just like:layer[n -> n] = relu: relu_layer_1?
and I config the spilt just like,but not use split layer?: 
layer[a -> a1]
layer[a -> a2]
layer[a -> a3]

because if found there some memory copy in the normal way, so, My network run little slowly compare with purine flamwork with the same network

**Comment by antinucleon** [comment]
We and purine's author are busy making next generation toolkit: https://github.com/antinucleon/mxnet
The problem doesn't exist in new toolkit. 
Thanks.

**Comment by junranhe** [comment]
I compare cxxnet with purine2, purine always fast than cxxnet... cxxnet is easy to understand, and purine is more fast, is hard to choice， so, If mxnet is easy to read and fast, I will try it
