### ISSUE TITLE
cudnn_convolution_layer : Is it  cost a lost of temp memory?

### ISSUE THREAD

**Issue by junranhe** [dmlc/cxxnet#234]
I found every cudnn_convolution_layer has in depend memory: temp_ ? It will use too memory in my GT780, I think it must to use SPECIFY_WORKSPACE_LIMIT to choice the memory size, and set the shared memory to convolution layer in the same thread

**Comment by antinucleon** [comment]
This is fixed in mxnet. We hope to finish mxnet as soon as possible

**Comment by junranhe** [comment]
so cxxnet is never fix the bug?

**Comment by junranhe** [comment]
Ok,I see
