### ISSUE TITLE
Train ImageNet on Windows Server, the error rate dose not decrease

### ISSUE THREAD

**Issue by ommiissyu** [dmlc/cxxnet#236]
Hi,

I have use cxxnet on the Windows Server with 2 K40 to train the ImageNet2012 data. I used the kaiming.conf and Inception-BN.conf, and I found that the error rate did not decrease. I have tried to use the cudnn v3 and not to use cudnn v3. The issues were the same. Does anyone have the same issue as mine?

**Comment by superzrx** [comment]
@ommiissyu do you use im2rec ? is file list shuffled?

**Comment by ommiissyu** [comment]
@superzrx ,I use both im2rec and im2bin, the results are the same.

**Comment by ommiissyu** [comment]
@superzrx ,when i train the model, I use the shuffle, but when generate the bin or rec file, I don't shuffle the list. I will try shuffle the list when using the im2rec. Thank you.
