### ISSUE TITLE
why the const kDataKeyStep equals 4?

### ISSUE THREAD

**Issue by DrustZ** [dmlc/cxxnet#237]
Hi I noticed that in ``updater.h`` the const ``kDataKeyStep = 4``, 
but in the following lines only 0 and 1 are used
```
  if (!strcmp(tag, "bias")) return layer_index * kDataKeyStep + 1;
  if (!strcmp(tag, "wmat")) return layer_index * kDataKeyStep + 0;
```
I wonder if I could use 2 or 3 for other propose? are they free to use?
@mli @winstywang @tqchen

**Comment by DrustZ** [comment]
@antinucleon

**Comment by tqchen** [comment]
Yes, all the encoding will be used throw this function, so you are free to change it

**Comment by DrustZ** [comment]
Thanks, I'll try.

**Comment by DrustZ** [comment]
Hi, I've tried to add another weight to be update
```
  if (!strcmp(tag, "weight")) return layer_index * kDataKeyStep + 2;
```
and added other corresponding codes like ``decode`` ``encode`` ``applyvisitor``
however, the weight seems never to be updated...
The initial two (``bias`` and ``wmat_``) works fine.
thanks, @tqchen .

**Comment by DrustZ** [comment]
My fault, it works~
