### ISSUE TITLE
CXXnet build.sh error no matching function for call to ‘unpack_patch2col

### ISSUE THREAD

**Issue by JasZhanAva** [dmlc/cxxnet#248]
I used opencv3.1.0 and openblas 0.2.14 and tried several times, it always occur no matching function for call to ‘unpack_patch2col

In file included from src/layer/layer_impl-inl.hpp:10:0,
                 from src/layer/layer_impl.cpp:7:
src/layer/./convolution_layer-inl.hpp: In instantiation of ‘void cxxnet::layer::ConvolutionLayer<xpu>::Forward(bool, const std::vectorcxxnet::layer::Node<xpu_>&, const std::vectorcxxnet::layer::Node<xpu_>&, cxxnet::layer::ConnectState<xpu>_) [with xpu = mshadow::cpu]’:
src/layer/layer_impl.cpp:18:1:   required from here
src/layer/./convolution_layer-inl.hpp:87:115: error: no matching function for call to ‘unpack_patch2col(mshadow::Tensor<mshadow::cpu, 4, float>, int&, int&, int&)’
         temp_col_ = unpack_patch2col(in.Slice(i, i+step), param_.kernel_height, param_.kernel_width, param_.stride);
                                                                                                                   ^
src/layer/./convolution_layer-inl.hpp:87:115: note: candidates are:
In file included from ./mshadow/mshadow/./extension.h:12:0,
                 from ./mshadow/mshadow/tensor.h:793,
                 from src/layer/./layer.h:12,
                 from src/layer/layer_impl-inl.hpp:8,
                 from src/layer/layer_impl.cpp:7:
./mshadow/mshadow/././extension/unpack_patch2col.h:91:1: note: template<class SrcExp, class DType, int etype> mshadow::expr::UnpackPatchToColXExp<SrcExp, DType, mshadow::expr::ExpInfo<E>::kDim> mshadow::expr::unpack_patch2col(const mshadow::expr::Exp<SrcExp, DType, etype>&, mshadow::index_t, mshadow::index_t, mshadow::index_t, mshadow::index_t)
 unpack_patch2col(const Exp<SrcExp, DType, etype> &img,
 ^
./mshadow/mshadow/././extension/unpack_patch2col.h:91:1: note:   template argument deduction/substitution failed:
In file included from src/layer/layer_impl-inl.hpp:10:0,
                 from src/layer/layer_impl.cpp:7:
src/layer/./convolution_layer-inl.hpp:87:115: note:   candidate expects 5 arguments, 4 provided
         temp_col_ = unpack_patch2col(in.Slice(i, i+step), param_.kernel_height, param_.kernel_width, param_.stride);
                                                                                                                   ^
In file included from ./mshadow/mshadow/./extension.h:12:0,
                 from ./mshadow/mshadow/tensor.h:793,
                 from src/layer/./layer.h:12,
                 from src/layer/layer_impl-inl.hpp:8,
                 from src/layer/layer_impl.cpp:7:
./mshadow/mshadow/././extension/unpack_patch2col.h:104:1: note: template<class SrcExp, class DType, int etype> mshadow::expr::UnpackPatchToColXExp<SrcExp, DType, mshadow::expr::ExpInfo<E>::kDim> mshadow::expr::unpack_patch2col(const mshadow::expr::Exp<SrcExp, DType, etype>&, mshadow::index_t, mshadow::index_t, mshadow::index_t, mshadow::index_t, mshadow::index_t, mshadow::index_t)
 unpack_patch2col(const Exp<SrcExp, DType, etype> &img,
 ^
./mshadow/mshadow/././extension/unpack_patch2col.h:104:1: note:   template argument deduction/substitution failed:
In file included from src/layer/layer_impl-inl.hpp:10:0,
                 from src/layer/layer_impl.cpp:7:
src/layer/./convolution_layer-inl.hpp:87:115: note:   candidate expects 7 arguments, 4 provided
         temp_col_ = unpack_patch2col(in.Slice(i, i+step), param_.kernel_height, param_.kernel_width, param_.stride);
                                                                                                                   ^
src/layer/./convolution_layer-inl.hpp:90:94: error: no matching function for call to ‘unpack_patch2col(mshadow::expr::PaddingExp<mshadow::Tensor<mshadow::cpu, 4, float>, float, 4>, int&, int&, int&)’
                                      param_.kernel_height, param_.kernel_width, param_.stride);
                                                                                              ^
src/layer/./convolution_layer-inl.hpp:90:94: note: candidates are:
In file included from ./mshadow/mshadow/./extension.h:12:0,
                 from ./mshadow/mshadow/tensor.h:793,
                 from src/layer/./layer.h:12,
                 from src/layer/layer_impl-inl.hpp:8,
                 from src/layer/layer_impl.cpp:7:
./mshadow/mshadow/././extension/unpack_patch2col.h:91:1: note: template<class SrcExp, class DType, int etype> mshadow::expr::UnpackPatchToColXExp<SrcExp, DType, mshadow::expr::ExpInfo<E>::kDim> mshadow::expr::unpack_patch2col(const mshadow::expr::Exp<SrcExp, DType, etype>&, mshadow::index_t, mshadow::index_t, mshadow::index_t, mshadow::index_t)
 unpack_patch2col(const Exp<SrcExp, DType, etype> &img,
 ^
./mshadow/mshadow/././extension/unpack_patch2col.h:91:1: note:   template argument deduction/substitution failed:
In file included from src/layer/layer_impl-inl.hpp:10:0,
                 from src/layer/layer_impl.cpp:7:
src/layer/./convolution_layer-inl.hpp:90:94: note:   candidate expects 5 arguments, 4 provided
                                      param_.kernel_height, param_.kernel_width, param_.stride);
                                                                                              ^
In file included from ./mshadow/mshadow/./extension.h:12:0,
                 from ./mshadow/mshadow/tensor.h:793,
                 from src/layer/./layer.h:12,
                 from src/layer/layer_impl-inl.hpp:8,
                 from src/layer/layer_impl.cpp:7:
./mshadow/mshadow/././extension/unpack_patch2col.h:104:1: note: template<class SrcExp, class DType, int etype> mshadow::expr::UnpackPatchToColXExp<SrcExp, DType, mshadow::expr::ExpInfo<E>::kDim> mshadow::expr::unpack_patch2col(const mshadow::expr::Exp<SrcExp, DType, etype>&, mshadow::index_t, mshadow::index_t, mshadow::index_t, mshadow::index_t, mshadow::index_t, mshadow::index_t)
 unpack_patch2col(const Exp<SrcExp, DType, etype> &img,
 ^
./mshadow/mshadow/././extension/unpack_patch2col.h:104:1: note:   template argument deduction/substitution failed:
In file included from src/layer/layer_impl-inl.hpp:10:0,
                 from src/layer/layer_impl.cpp:7:
src/layer/./convolution_layer-inl.hpp:90:94: note:   candidate expects 7 arguments, 4 provided
                                      param_.kernel_height, param_.kernel_width, param_.stride);
                                                                                              ^
src/layer/./convolution_layer-inl.hpp: In instantiation of ‘void cxxnet::layer::ConvolutionLayer<xpu>::Backprop(bool, const std::vectorcxxnet::layer::Node<xpu_>&, const std::vectorcxxnet::layer::Node<xpu_>&, cxxnet::layer::ConnectState<xpu>_) [with xpu = mshadow::cpu]’:
src/layer/layer_impl.cpp:18:1:   required from here
src/layer/./convolution_layer-inl.hpp:130:117: error: no matching function for call to ‘unpack_patch2col(mshadow::Tensor<mshadow::cpu, 4, float>, int&, int&, int&)’
         temp_col_ = unpack_patch2col(in.Slice(i, i + step), param_.kernel_height, param_.kernel_width, param_.stride);
                                                                                                                     ^
src/layer/./convolution_layer-inl.hpp:130:117: note: candidates are:
In file included from ./mshadow/mshadow/./extension.h:12:0,
                 from ./mshadow/mshadow/tensor.h:793,
                 from src/layer/./layer.h:12,
                 from src/layer/layer_impl-inl.hpp:8,
                 from src/layer/layer_impl.cpp:7:
./mshadow/mshadow/././extension/unpack_patch2col.h:91:1: note: template<class SrcExp, class DType, int etype> mshadow::expr::UnpackPatchToColXExp<SrcExp, DType, mshadow::expr::ExpInfo<E>::kDim> mshadow::expr::unpack_patch2col(const mshadow::expr::Exp<SrcExp, DType, etype>&, mshadow::index_t, mshadow::index_t, mshadow::index_t, mshadow::index_t)
 unpack_patch2col(const Exp<SrcExp, DType, etype> &img,
 ^
./mshadow/mshadow/././extension/unpack_patch2col.h:91:1: note:   template argument deduction/substitution failed:
In file included from src/layer/layer_impl-inl.hpp:10:0,
                 from src/layer/layer_impl.cpp:7:
src/layer/./convolution_layer-inl.hpp:130:117: note:   candidate expects 5 arguments, 4 provided
         temp_col_ = unpack_patch2col(in.Slice(i, i + step), param_.kernel_height, param_.kernel_width, param_.stride);
                                                                                                                     ^
In file included from ./mshadow/mshadow/./extension.h:12:0,
                 from ./mshadow/mshadow/tensor.h:793,
                 from src/layer/./layer.h:12,
                 from src/layer/layer_impl-inl.hpp:8,
                 from src/layer/layer_impl.cpp:7:
./mshadow/mshadow/././extension/unpack_patch2col.h:104:1: note: template<class SrcExp, class DType, int etype> mshadow::expr::UnpackPatchToColXExp<SrcExp, DType, mshadow::expr::ExpInfo<E>::kDim> mshadow::expr::unpack_patch2col(const mshadow::expr::Exp<SrcExp, DType, etype>&, mshadow::index_t, mshadow::index_t, mshadow::index_t, mshadow::index_t, mshadow::index_t, mshadow::index_t)
 unpack_patch2col(const Exp<SrcExp, DType, etype> &img,
 ^
./mshadow/mshadow/././extension/unpack_patch2col.h:104:1: note:   template argument deduction/substitution failed:
In file included from src/layer/layer_impl-inl.hpp:10:0,
                 from src/layer/layer_impl.cpp:7:
src/layer/./convolution_layer-inl.hpp:130:117: note:   candidate expects 7 arguments, 4 provided
         temp_col_ = unpack_patch2col(in.Slice(i, i + step), param_.kernel_height, param_.kernel_width, param_.stride);
                                                                                                                     ^
In file included from src/layer/layer_impl-inl.hpp:10:0,
                 from src/layer/layer_impl.cpp:7:
src/layer/./convolution_layer-inl.hpp:132:148: error: no matching function for call to ‘unpack_patch2col(mshadow::expr::PaddingExp<mshadow::Tensor<mshadow::cpu, 4, float>, float, 4>, int&, int&, int&)’
         temp_col_ = unpack_patch2col(pad(in.Slice(i,i + step),param_.pad_y, param_.pad_x), param_.kernel_height, param_.kernel_width, param_.stride);
                                                                                                                                                    ^
src/layer/./convolution_layer-inl.hpp:132:148: note: candidates are:
In file included from ./mshadow/mshadow/./extension.h:12:0,
                 from ./mshadow/mshadow/tensor.h:793,
                 from src/layer/./layer.h:12,
                 from src/layer/layer_impl-inl.hpp:8,
                 from src/layer/layer_impl.cpp:7:
./mshadow/mshadow/././extension/unpack_patch2col.h:91:1: note: template<class SrcExp, class DType, int etype> mshadow::expr::UnpackPatchToColXExp<SrcExp, DType, mshadow::expr::ExpInfo<E>::kDim> mshadow::expr::unpack_patch2col(const mshadow::expr::Exp<SrcExp, DType, etype>&, mshadow::index_t, mshadow::index_t, mshadow::index_t, mshadow::index_t)
 unpack_patch2col(const Exp<SrcExp, DType, etype> &img,
 ^
./mshadow/mshadow/././extension/unpack_patch2col.h:91:1: note:   template argument deduction/substitution failed:
In file included from src/layer/layer_impl-inl.hpp:10:0,
                 from src/layer/layer_impl.cpp:7:
src/layer/./convolution_layer-inl.hpp:132:148: note:   candidate expects 5 arguments, 4 provided
         temp_col_ = unpack_patch2col(pad(in.Slice(i,i + step),param_.pad_y, param_.pad_x), param_.kernel_height, param_.kernel_width, param_.stride);
                                                                                                                                                    ^
In file included from ./mshadow/mshadow/./extension.h:12:0,
                 from ./mshadow/mshadow/tensor.h:793,
                 from src/layer/./layer.h:12,
                 from src/layer/layer_impl-inl.hpp:8,
                 from src/layer/layer_impl.cpp:7:
./mshadow/mshadow/././extension/unpack_patch2col.h:104:1: note: template<class SrcExp, class DType, int etype> mshadow::expr::UnpackPatchToColXExp<SrcExp, DType, mshadow::expr::ExpInfo<E>::kDim> mshadow::expr::unpack_patch2col(const mshadow::expr::Exp<SrcExp, DType, etype>&, mshadow::index_t, mshadow::index_t, mshadow::index_t, mshadow::index_t, mshadow::index_t, mshadow::index_t)
 unpack_patch2col(const Exp<SrcExp, DType, etype> &img,
 ^
./mshadow/mshadow/././extension/unpack_patch2col.h:104:1: note:   template argument deduction/substitution failed:
In file included from src/layer/layer_impl-inl.hpp:10:0,
                 from src/layer/layer_impl.cpp:7:
src/layer/./convolution_layer-inl.hpp:132:148: note:   candidate expects 7 arguments, 4 provided
         temp_col_ = unpack_patch2col(pad(in.Slice(i,i + step),param_.pad_y, param_.pad_x), param_.kernel_height, param_.kernel_width, param_.stride);
                                                                                                                                                    ^
src/layer/./convolution_layer-inl.hpp:148:144: error: no matching function for call to ‘pack_col2patch(mshadow::TensorContainer<mshadow::cpu, 2>&, mshadow::Shape<4>, int&, int&, int&)’
           in.Slice(i,i+step) = pack_col2patch(temp_col_, in.Slice(i, i + step).shape_, param_.kernel_height, param_.kernel_width, param_.stride);
                                                                                                                                                ^
src/layer/./convolution_layer-inl.hpp:148:144: note: candidates are:
In file included from ./mshadow/mshadow/./extension.h:13:0,
                 from ./mshadow/mshadow/tensor.h:793,
                 from src/layer/./layer.h:12,
                 from src/layer/layer_impl-inl.hpp:8,
                 from src/layer/layer_impl.cpp:7:
./mshadow/mshadow/././extension/pack_col2patch.h:72:1: note: template<class SrcExp, class DType, int dstdim, int etype> mshadow::expr::PackColToPatchXExp<SrcExp, DType, dstdim> mshadow::expr::pack_col2patch(const mshadow::expr::Exp<SrcExp, DType, etype>&, mshadow::Shape<dim>, mshadow::index_t, mshadow::index_t, mshadow::index_t, mshadow::index_t)
 pack_col2patch(const expr::Exp<SrcExp, DType, etype> &src,
 ^
./mshadow/mshadow/././extension/pack_col2patch.h:72:1: note:   template argument deduction/substitution failed:
In file included from src/layer/layer_impl-inl.hpp:10:0,
                 from src/layer/layer_impl.cpp:7:
src/layer/./convolution_layer-inl.hpp:148:144: note:   candidate expects 6 arguments, 5 provided
           in.Slice(i,i+step) = pack_col2patch(temp_col_, in.Slice(i, i + step).shape_, param_.kernel_height, param_.kernel_width, param_.stride);
                                                                                                                                                ^
In file included from ./mshadow/mshadow/./extension.h:13:0,
                 from ./mshadow/mshadow/tensor.h:793,
                 from src/layer/./layer.h:12,
                 from src/layer/layer_impl-inl.hpp:8,
                 from src/layer/layer_impl.cpp:7:
./mshadow/mshadow/././extension/pack_col2patch.h:88:1: note: template<class SrcExp, class DType, int dstdim, int etype> mshadow::expr::PackColToPatchXExp<SrcExp, DType, dstdim> mshadow::expr::pack_col2patch(const mshadow::expr::Exp<SrcExp, DType, etype>&, mshadow::Shape<dim>, mshadow::index_t, mshadow::index_t, mshadow::index_t, mshadow::index_t, mshadow::index_t, mshadow::index_t)
 pack_col2patch(const expr::Exp<SrcExp, DType, etype> &src,
 ^
./mshadow/mshadow/././extension/pack_col2patch.h:88:1: note:   template argument deduction/substitution failed:
In file included from src/layer/layer_impl-inl.hpp:10:0,
                 from src/layer/layer_impl.cpp:7:
src/layer/./convolution_layer-inl.hpp:148:144: note:   candidate expects 8 arguments, 5 provided
           in.Slice(i,i+step) = pack_col2patch(temp_col_, in.Slice(i, i + step).shape_, param_.kernel_height, param_.kernel_width, param_.stride);
                                                                                                                                                ^
src/layer/./convolution_layer-inl.hpp:152:130: error: no matching function for call to ‘pack_col2patch(mshadow::TensorContainer<mshadow::cpu, 2>&, mshadow::Shape<4>&, int&, int&, int&)’
           in.Slice(i, i + step) = crop(pack_col2patch(temp_col_, pshape, param_.kernel_height, param_.kernel_width, param_.stride), in[i][0].shape_);
                                                                                                                                  ^
src/layer/./convolution_layer-inl.hpp:152:130: note: candidates are:
In file included from ./mshadow/mshadow/./extension.h:13:0,
                 from ./mshadow/mshadow/tensor.h:793,
                 from src/layer/./layer.h:12,
                 from src/layer/layer_impl-inl.hpp:8,
                 from src/layer/layer_impl.cpp:7:
./mshadow/mshadow/././extension/pack_col2patch.h:72:1: note: template<class SrcExp, class DType, int dstdim, int etype> mshadow::expr::PackColToPatchXExp<SrcExp, DType, dstdim> mshadow::expr::pack_col2patch(const mshadow::expr::Exp<SrcExp, DType, etype>&, mshadow::Shape<dim>, mshadow::index_t, mshadow::index_t, mshadow::index_t, mshadow::index_t)
 pack_col2patch(const expr::Exp<SrcExp, DType, etype> &src,
 ^
./mshadow/mshadow/././extension/pack_col2patch.h:72:1: note:   template argument deduction/substitution failed:
In file included from src/layer/layer_impl-inl.hpp:10:0,
                 from src/layer/layer_impl.cpp:7:
src/layer/./convolution_layer-inl.hpp:152:130: note:   candidate expects 6 arguments, 5 provided
           in.Slice(i, i + step) = crop(pack_col2patch(temp_col_, pshape, param_.kernel_height, param_.kernel_width, param_.stride), in[i][0].shape_);
                                                                                                                                  ^
In file included from ./mshadow/mshadow/./extension.h:13:0,
                 from ./mshadow/mshadow/tensor.h:793,
                 from src/layer/./layer.h:12,
                 from src/layer/layer_impl-inl.hpp:8,
                 from src/layer/layer_impl.cpp:7:
./mshadow/mshadow/././extension/pack_col2patch.h:88:1: note: template<class SrcExp, class DType, int dstdim, int etype> mshadow::expr::PackColToPatchXExp<SrcExp, DType, dstdim> mshadow::expr::pack_col2patch(const mshadow::expr::Exp<SrcExp, DType, etype>&, mshadow::Shape<dim>, mshadow::index_t, mshadow::index_t, mshadow::index_t, mshadow::index_t, mshadow::index_t, mshadow::index_t)
 pack_col2patch(const expr::Exp<SrcExp, DType, etype> &src,
 ^
./mshadow/mshadow/././extension/pack_col2patch.h:88:1: note:   template argument deduction/substitution failed:
In file included from src/layer/layer_impl-inl.hpp:10:0,
                 from src/layer/layer_impl.cpp:7:
src/layer/./convolution_layer-inl.hpp:152:130: note:   candidate expects 8 arguments, 5 provided
           in.Slice(i, i + step) = crop(pack_col2patch(temp_col_, pshape, param_.kernel_height, param_.kernel_width, param_.stride), in[i][0].shape_);
                                                                                                                                  ^
In file included from ./mshadow/mshadow-ps/./ps_local-inl.h:24:0,
                 from ./mshadow/mshadow-ps/mshadow_ps.h:328,
                 from src/nnet/./../updater/updater.h:6,
                 from src/nnet/./neural_net-inl.hpp:14,
                 from src/nnet/nnet_impl-inl.hpp:9,
                 from src/nnet/nnet_impl.cpp:4:
./mshadow/mshadow-ps/././thread_util.h: In instantiation of ‘TValue& mshadow::utils::ThreadSafeMap<TValue>::GetRef(int) [with TValue = mshadow::ps::LocalModel<mshadow::cpu, float>::PushEntry]’:
./mshadow/mshadow-ps/./ps_local-inl.h:233:39:   required from ‘void mshadow::ps::LocalModel<xpu, DType>::SetWeight_(mshadow::Tensor<Device, 2, DType>, int, int) [with xpu = mshadow::cpu; DType = float]’
src/nnet/nnet_impl.cpp:13:1:   required from here
./mshadow/mshadow-ps/././thread_util.h:150:5: warning: passing NULL to non-pointer argument 1 of ‘long int google::GetReferenceableValue(long int)’ [-Wconversion-null]
     CHECK_NE(ret, NULL) << "key = " << key << " does not exist";
     ^
./mshadow/mshadow-ps/././thread_util.h: In instantiation of ‘TValue& mshadow::utils::ThreadSafeMap<TValue>::GetRef(int) [with TValue = mshadow::ps::LocalModel<mshadow::cpu, float>::PullEntry]’:
./mshadow/mshadow-ps/./ps_local-inl.h:290:39:   required from ‘void mshadow::ps::LocalModel<xpu, DType>::Push_(mshadow::Tensor<Device, 2, DType>, int, int, int) [with xpu = mshadow::cpu; DType = float]’
src/nnet/nnet_impl.cpp:13:1:   required from here
./mshadow/mshadow-ps/././thread_util.h:150:5: warning: passing NULL to non-pointer argument 1 of ‘long int google::GetReferenceableValue(long int)’ [-Wconversion-null]
In file included from ./mshadow/mshadow/././logging.h:47:0,
                 from ./mshadow/mshadow/./stream_gpu-inl.h:11,
                 from ./mshadow/mshadow/tensor.h:792,
                 from src/nnet/./nnet.h:10,
                 from src/nnet/nnet_impl-inl.hpp:6,
                 from src/nnet/nnet_impl.cpp:4:
/usr/include/glog/logging.h: In instantiation of ‘std::string\* google::Check_NEImpl(const T1&, const T2&, const char_) [with T1 = mshadow::ps::LocalModel<mshadow::cpu, float>::PushEntry_; T2 = long int; std::string = std::basic_string<char>]’:
./mshadow/mshadow-ps/././thread_util.h:150:5:   required from ‘TValue& mshadow::utils::ThreadSafeMap<TValue>::GetRef(int) [with TValue = mshadow::ps::LocalModel<mshadow::cpu, float>::PushEntry]’
./mshadow/mshadow-ps/./ps_local-inl.h:233:39:   required from ‘void mshadow::ps::LocalModel<xpu, DType>::SetWeight_(mshadow::Tensor<Device, 2, DType>, int, int) [with xpu = mshadow::cpu; DType = float]’
src/nnet/nnet_impl.cpp:13:1:   required from here
/usr/include/glog/logging.h:695:1: error: ISO C++ forbids comparison between pointer and integer [-fpermissive]
 DEFINE_CHECK_OP_IMPL(Check_NE, !=)  // Use CHECK(x == NULL) instead.
 ^
/usr/include/glog/logging.h: In instantiation of ‘std::string\* google::Check_NEImpl(const T1&, const T2&, const char_) [with T1 = mshadow::ps::LocalModel<mshadow::cpu, float>::PullEntry_; T2 = long int; std::string = std::basic_string<char>]’:
./mshadow/mshadow-ps/././thread_util.h:150:5:   required from ‘TValue& mshadow::utils::ThreadSafeMap<TValue>::GetRef(int) [with TValue = mshadow::ps::LocalModel<mshadow::cpu, float>::PullEntry]’
./mshadow/mshadow-ps/./ps_local-inl.h:290:39:   required from ‘void mshadow::ps::LocalModel<xpu, DType>::Push_(mshadow::Tensor<Device, 2, DType>, int, int, int) [with xpu = mshadow::cpu; DType = float]’
src/nnet/nnet_impl.cpp:13:1:   required from here
/usr/include/glog/logging.h:695:1: error: ISO C++ forbids comparison between pointer and integer [-fpermissive]
make: **\* [nnet_cpu.o] Error 1

**Comment by tqchen** [comment]
this project is deprecated, please see https://github.com/dmlc/mxnet instead
