### ISSUE TITLE
Tutorial and documentation

### ISSUE THREAD

**Issue by neogi** [dmlc/cxxnet#30]
Hello,

I was looking into the kaggle example file bowl.conf. An extract is pasted below:
...
layer[0->1] = conv
kernel_size = 5
stride = 4
nchannel = 96
pad = 2
layer[1->2] = relu
layer[2->3] = max_pooling
kernel_size = 3
stride = 2
###############
layer[3->4] = conv
nchannel = 128
kernel_size = 3
pad = 2
...
I found the keyword 'pad'. I could not find any details in the documentation. Could you please mention the meaning of this parameter?

Thank you.

**Comment by TELSER1** [comment]
I'm a little late, but you can find an explanation here: 
http://vision.stanford.edu/teaching/cs231n/slides/lecture7.pdf
