### ISSUE TITLE
Fail to build on OSX

### ISSUE THREAD

**Issue by vkuznet** [dmlc/cxxnet#41]
Hi, I'm trying to build cxxnet on OSX using recent CUDA (6.5). The problem I face seems to be related to boost/CUDA issue reported here (https://svn.boost.org/trac/boost/ticket/10418), but I did check that my latest boost had the fix mentioned there. Anyway, here is my build issue:

Fetch mshadow...
fatal: destination path 'mshadow' already exists and is not an empty directory.
nvcc -c -o cxxnet_nnet_gpu.o --use_fast_math -g -O3 -ccbin g++ -Xcompiler "-Wall -g -O3 -msse3 -Wno-unknown-pragmas -funroll-loops -I/opt/local/include -I/Developer/NVIDIA/CUDA-6.5/include/ -I./mshadow -DMSHADOW_USE_MKL=0 -DMSHADOW_USE_CBLAS=1" cxxnet/nnet/cxxnet_nnet.cu
/opt/local/include/gcc48/c++/cstdlib(178): error: identifier "__int128" is undefined
/opt/local/include/gcc48/c++/cstdlib(179): error: identifier "__int128" is undefined

Do you have any idea how to fix this?
Thanks,
Valentin.

**Comment by mingloo** [comment]
Hi Valentin,

I've met the same problem as you on OSX with CUDA-6.5.  Now, everything goes well after I've compiled the whole project with CUDA-7.0. Also, you need to be care of the version compiler(gcc/g++) on your Mac.

The detailed guide can be found at [NVIDIA CUDA Getting Started Guide for Mac OS X](http://docs.nvidia.com/cuda/cuda-getting-started-guide-for-mac-os-x/#axzz3WLin5WIL).

I think this may help you. :)

Thanks
Ming

**Comment by vkuznet** [comment]
Hi Ming,
yes, I confirm that I can build it on OSX with CUDA-7.0 and using clang/clang++
compiler (gcc/g++ didn't work).
Valentin.
