### ISSUE TITLE
V2-Refactor How to predict for Kaggle Bowl (pred_raw gone)

### ISSUE THREAD

**Issue by johnswan** [dmlc/cxxnet#47]
Hi,

I noticed that pred_raw has gone, but pred does not produce the same amount of data (and only one column).

If I use extract with extract_node_name = top[-1], then I get predicted data of the correct size and format, but the Kaggle leaderboard score is very bad (27!).

How do we predict for kaggle_bowl?

Thanks

**Comment by antinucleon** [comment]
I am using V2 generating submission too, The config should be:
```
model_in = xxx
task = extract
extract_node_name = top[-1]
output_format = txt
````
Please verify two things: 
1. Whether the submission file is correct
2. Whether your model is correct.

**Comment by DataCentric1** [comment]
I had the same issue and this helped. Thanks!
