### ISSUE TITLE
error while run python example mnist.py

### ISSUE THREAD

**Issue by yanqingmen** [dmlc/cxxnet#53]
I got the following error message when trying python example mnist.py
Traceback (most recent call last):
  File "mnist.py", line 50, in <module>
    net = cxxnet.train(cfg, data, 1, param, eval_data = deval)
TypeError: train() got an unexpected keyword argument 'eval_data'

this may be caused by two "train" method in python wrapper 'cxxnet.py', since the last "train" method will cover the previous one.

**Comment by antinucleon** [comment]
Thanks now it is fixed.
