### ISSUE TITLE
Does this lib support the spatial pyramid pooling as in  He Kaiming's SPP net ?

### ISSUE THREAD

**Issue by YangXS** [dmlc/cxxnet#56]

**Comment by winstywang** [comment]
You can implement it easily using split and concat layer.

**Comment by YangXS** [comment]
@winstywang, thanks for your help. I want to train the model on data with different scale. I do not want to resize,  Could you give some advice for training with various scale images?

**Comment by winstywang** [comment]
One workaround is that you pad the each input to the largest image in the dataset, or you can pad it in the iterator. Supporting different image size in one batch is inefficient for implementation.
