### ISSUE TITLE
rookie's question about how to set up binary classification

### ISSUE THREAD

**Issue by mrfipwa** [dmlc/cxxnet#57]
sorry if this sounds too rudimentary.

I am learning the CNN and tried to use cxxnet for some test runs. I tried to set up a simple classification test run, just for sanity check but doesn't seem get the right result. The labels are just 0 and 1 and images are 25x25 pixels. I modified my run from the MNIST example

here is my configuration file

```
# training iterator
data = train
iter = mnist
    path_img = "../PrepareData/train_image.gz"
    path_label = "../PrepareData/train_label.gz"
    input_flat = 0
    shuffle = 1
iter = end
# evaluation iterator
eval = test
iter = mnist
    input_flat = 0
    path_img = "../PrepareData/test_image.gz"
    path_label = "../PrepareData/test_label.gz"
iter = end

netconfig=start
layer[0->1] = conv:cv1
  kernel_size = 4
  pad = 0
  stride = 1
  nchannel = 32
  random_type = xavier
  no_bias=0
layer[1->2] = max_pooling
  kernel_size = 2
  stride = 2
layer[2->3] = flatten
layer[3->3] = dropout
  threshold = 0.5
layer[3->4] = fullc:fc1
  nhidden = 100
  init_sigma = 0.01
layer[4->5] = sigmoid:se1
layer[5->6] = fullc:fc2
  nhidden = 10
  init_sigma = 0.01
layer[6->6] = softmax
netconfig=end

# input shape not including batch
input_shape = 1,25,25
batch_size = 100

## global parameters
dev = cpu
save_model = 15
max_round = 15
num_round = 15
train_eval = 1
random_type = gaussian
## learning parameters
eta = 0.1
momentum = 0.9
wd  = 0.0
# evaluation metric
#metric = logloss
metric = error
eval_train = 1
# end of config
--------------------------------------------------------------------

and here is the output

--------------------------------------------------------------------
finish initialization with 1 devices
Initializing layer: cv1
Initializing layer: 1
Initializing layer: 2
Initializing layer: 3
Initializing layer: fc1
Initializing layer: se1
Initializing layer: fc2
Initializing layer: 7
SGDUpdater: eta=0.100000, mom=0.900000
SGDUpdater: eta=0.100000, mom=0.900000
SGDUpdater: eta=0.100000, mom=0.900000
SGDUpdater: eta=0.100000, mom=0.900000
SGDUpdater: eta=0.100000, mom=0.900000
SGDUpdater: eta=0.100000, mom=0.900000
node[in].shape: 100,1,25,25
node[1].shape: 100,32,22,22
node[2].shape: 100,32,11,11
node[3].shape: 100,1,1,3872
node[4].shape: 100,1,1,100
node[5].shape: 100,1,1,100
node[6].shape: 100,1,1,10
MNISTIterator: load 38376 images, shuffle=1, shape=100,1,25,25
MNISTIterator: load 38377 images, shuffle=0, shape=100,1,25,25
initializing end, start working
update round 0
round        0:[     300] 52 sec elapsed[1]     train-error:0.166554    test-error:0.0373629
round        1:[     300] 139 sec elapsed[2]    train-error:0.0303655   test-error:0.0174674
round        2:[     300] 225 sec elapsed[3]    train-error:0.180522    test-error:0.501018
round        3:[     300] 310 sec elapsed[4]    train-error:0.500235    test-error:0.501018
round        4:[     300] 392 sec elapsed[5]    train-error:0.500235    test-error:0.501018
round        5:[     300] 473 sec elapsed[6]    train-error:0.500235    test-error:0.501018
round        6:[     300] 554 sec elapsed[7]    train-error:0.500235    test-error:0.501018
round        7:[     300] 641 sec elapsed[8]    train-error:0.500235    test-error:0.501018
round        8:[     300] 720 sec elapsed[9]    train-error:0.500235    test-error:0.501018
round        9:[     300] 802 sec elapsed[10]   train-error:0.500235    test-error:0.501018

```

Basically the training error "converges" to 0.5:-(

I tried to use only 1 or 2 unit at output layer, and change the metric to logloss but seems always get the same "converged" training error. can you see if I made some stupid mistakes

Thanks

**Comment by tqchen** [comment]
If it was binary label, normally you want to set final layer's hidden unit to be 2. Also make sure if you are using the right format for MNIST dataset, if you are using the mnist iterator.

**Comment by mrfipwa** [comment]
Thanks for such quick reply. I change the final layer's hidden unit to be 2 and got the same problem. Is there a way to check if my data is in correct format? I have tried to match the format but may have made mistakes. If you can suggest some way to debug this it will be great

also if I don't use MNIST iterator, is there an alternative way to input the data?


node[in].shape: 100,1,25,25
node[1].shape: 100,32,22,22
node[2].shape: 100,32,11,11
node[3].shape: 100,1,1,3872
node[4].shape: 100,1,1,100
node[5].shape: 100,1,1,100
node[6].shape: 100,1,1,2
MNISTIterator: load 38376 images, shuffle=1, shape=100,1,25,25
MNISTIterator: load 38377 images, shuffle=0, shape=100,1,25,25
initializing end, start working
round        0:[     300] 52 sec elapsed[1]     train-error:0.140026    test-error:0.0349869
round        1:[     300] 137 sec elapsed[2]    train-error:0.249164    test-error:0.501018
round        2:[     300] 224 sec elapsed[3]    train-error:0.500235    test-error:0.501018
round        3:[     300] 312 sec elapsed[4]    train-error:0.500235    test-error:0.501018
round        4:[     300] 395 sec elapsed[5]    train-error:0.500235    test-error:0.501018
round        5:[     300] 484 sec elapsed[6]    train-error:0.500235    test-error:0.501018

**Comment by winstywang** [comment]
This may be caused by improper initialization and large learning rate. Try set different seed and seed_data in global setting, and reduce the learning rate.

**Comment by tqchen** [comment]
if you have images, you can try using the image iterator, check out the kaggle bowl example

**Comment by mrfipwa** [comment]
Thanks. I will try to reduce the learning rate. I am currently reduce the eta and incrase the wd. what else should I change?

**Comment by mrfipwa** [comment]
so it seems changing the learning rate give me pretty reasonable results now. so I have a separate question. Once the model is trained, how to use cxxnet to apply the trained model on some new data? I am just lazy to check all the examples:-)

Thanks

**Comment by winstywang** [comment]
using task=pred, check the docs/task.md for details
