### ISSUE TITLE
The new cudnn convolution code still cannot be compiled in VS2012

### ISSUE THREAD

**Issue by happynear** [dmlc/cxxnet#58]
The gpu-specialize code in cudnn_convolution_layer-inl.hpp still has some problem. I think that the gpu-specialize code should be wrote in a independent .cuh header file, not in a .hpp one.  When the c/c++ compiler visit the hpp file, it would also try to complie the gpu codes, which causes error on the cuda kernels. Now I just cut all the codes from layer_impl.cpp to layer_impl.cu, in order to use nvcc to compile all the cpu/gpu codes. Hope for a better solution.

**Comment by antinucleon** [comment]
Thanks first. New code should be able to avoid the problem because we use template specialization for gpu part. Because I don't have Windows machine, I am not sure what VS2012 will do while template specialization. But I will take a look when I have chance.

**Comment by tqchen** [comment]
Thanks fr reporting the issue. This was due to CUDACC defined during CPU compilation.  I have add a macro guard CXXNET_COMPILE_CPU in newest master to prevent this. Please check and see if it works

**Comment by happynear** [comment]
The new code works. Thank you all.

**Comment by tqchen** [comment]
I am glad that it works out for you:) Thanks for using cxxnet

**Comment by happynear** [comment]
I'm sorry I mistaken the role of _CUDACC_. The old code could also work. Please roll back to the last version. Sorry again.

**Comment by tqchen** [comment]
No worries, I am glad that it works for you:)
