### ISSUE TITLE
how to get raw output from the network

### ISSUE THREAD

**Issue by mrfipwa** [dmlc/cxxnet#64]
Hi

Is there a way to get the raw output from the output? I tried to use the "pred" keyword and it only gives me the classified output

Thanks

**Comment by antinucleon** [comment]
You need to use the task extract feature: https://github.com/dmlc/cxxnet/blob/master/doc/tasks.md#extract-features

```
task = extract_feature
extract_node_name = top[-1]
model_in = ./models/0014.model
# this will extract last node, namely the softmax prediction.
```

**Comment by mrfipwa** [comment]
Thanks. I will try it.

**Comment by mrfipwa** [comment]
Hi

I have tried to add "task=extract_feature" but didn't get any output. Can you help?

Here is the portion of conf file I am using

# example configure file for mnist
# training iterator
pred = pred.txt
iter = mnist
    path_img = "./predict_image.gz"
    path_label = "./predict_fake_label.gz"
    input_flat = 0
iter = end

...


# this will extract last node, namely the softmax prediction.
task = extract_feature
extract_node_name = top[-1]
model_in = ../../models/0029.model

Thanks!
