### ISSUE TITLE
memory limitation of cxxnet?

### ISSUE THREAD

**Issue by mrfipwa** [dmlc/cxxnet#65]
Hi

I encountered another issue when using cxxnet for "pred" task. It seems to me the results are totally wrong once the memory consumption exceeds ~16GB. 

Basically I can build a model without any problem, and if I use small number of new data for "pred" task, then the results come out well. However, I noticed that once I use tons of new data for "pred", the results come out all 0. I did some experiments and it seems that as long as total memory consumption of the run is less than 16GB, then it is fine. Once it cross this boundary, the results are all wrong. Again, I am not sure if 16GB is the boundary, but it seems around that the code starts behave strangely.

I am running a CPU version of binary.

Thanks

**Comment by tqchen** [comment]
This should normally not be the case. Can I know what input iterator are you using?

Normally the prediction is done in a streaming matter if you use image or imgbin iterator, and it won't increase the memory consumption

**Comment by tqchen** [comment]
If you are hacking into mnist iterator's format. This could happen, because the mnist iterator uses tensor wihch use 32 bit unsigned int to save the space. I would recommend to switch to imgbin iterator, which is more standard. But you do remind us on this and we will make a fix.

Thanks!

**Comment by mrfipwa** [comment]
I used mnist iterator

I didn't hack into anything (haven't been able to understand the code yet:-))

32-bit explanation makes sense

I also noticed (well, I am not sure if I did it correctly or not) that when using mnist iterator for "pred" task, I have to supply some kind of the "fake-label". otherwise, the code won't proceed. If this is indeed the case, can you change the behavior? 

Thanks

**Comment by mrfipwa** [comment]
I will try to learn to use the imgbin iterator

**Comment by tqchen** [comment]
I would highly recommend you to switch to imgbin iterator, if you are working on images. Since it uses the streaming fashion loading and we optimize it a lot so you cost no extra memory even when training/predicting tones of data(say 1M jpeg images)

MNISTIterator was meant for MNIST dataset ...

**Comment by tqchen** [comment]
if you are packing your data using some languages, you might also want to try the wrapper. Say the python one, which allows you to directly make prediction for a batch of numpy array
