### ISSUE TITLE
Use cxxnet for classifiction other than images.

### ISSUE THREAD

**Issue by sachinvernekar** [dmlc/cxxnet#66]
How to use cxxnet for other than images say if an input has to be provided in the form of a .csv file- as in the case of Otto group challenge of Kaggle. In that case how do we generate .bin file? Can cxxnet be used for 1 dimensional convolutional neural network for speech?

**Comment by winstywang** [comment]
Check the recently added csv iterator and docs. It is a preliminary version, we will improve it in the future.

**Comment by sachinvernekar** [comment]
Thanks for quick reply. what about 1 dimensional convolution neural network, is it possible? I think it should be.

**Comment by winstywang** [comment]
Yes, you may use kernel_width and kernel_height to specify a rectangle kernel. We will update the doc soon.

**Comment by sachinvernekar** [comment]
Thank you very much.
