### ISSUE TITLE
im2bin can not work

### ISSUE THREAD

**Issue by OnlySang** [dmlc/cxxnet#67]
I tried im2col to transform image to binary file. but it always say "an not open file " /path/to/*.jpg.

**Comment by antinucleon** [comment]
In most of cases, it is because your image_root + path in lst file point to wrong place. Check this example for help. https://github.com/dmlc/cxxnet/tree/master/example/kaggle_bowl

**Comment by OnlySang** [comment]
@antinucleon It's not that case. I verified the path.
![2015-03-25 10 39 23](https://cloud.githubusercontent.com/assets/4698897/6817446/64dd0b8c-d2db-11e4-9ce2-60855b0865e0.png)

**Comment by antinucleon** [comment]
I think you make it wrong. I guess your list file path should be like ```./data/resize/42/xxx.jpg```. If it so, the right command should be ```../../tools/im2bin data/NameList.train ./ ./data/train.bin```

**Comment by OnlySang** [comment]
@antinucleon not like that. My list file is 42/xxx.jpg. and the image root is './data/resize/'. Your code use fopen64 to judge if open succeed. So wried!
What's more, output information's format have some problem.
