### ISSUE TITLE
Error "Incorrect Device ID" on running kaggle_bowl

### ISSUE THREAD

**Issue by apeeyush** [dmlc/cxxnet#68]
I tried running MNIST and kaggle_bowl example on an AWS GPU. I was able to successfully run the MNIST example but got an error message saying

    Error "Incorrect Device ID" on running kaggle_bowl

on running kaggle_bowl.

However, I was able to run the kaggle_bowl example around a week ago!

Could you please help with where the problem might be?

**Comment by antinucleon** [comment]
Please check your cuda configuration and ```dev``` setting. MNIST.conf is a CPU model.

**Comment by apeeyush** [comment]
I ran the MNIST_CONV.conf file which is a GPU model. I am guessing it is some issue with OpenCV, however I am not sure!

**Comment by antinucleon** [comment]
The error is not related to opencv. Check whether in the configuration there is two gpu selected by you only have one.

**Comment by apeeyush** [comment]
I ran the code just after cloning from Github. It appears that the conf file contains 1 GPU by default.

**Comment by antinucleon** [comment]
I will check it later today. The example is written before V2, so there may be some issues. Thanks

**Comment by apeeyush** [comment]
I forgot to update the cloned repo (which I did last time when I successfully ran kaggle_bowl). Maybe this is causing the error. I'll try running the code after updating the repo.

**Comment by antinucleon** [comment]
You need to use new mshadow from dmlc and new cxxnet.

**Comment by apeeyush** [comment]
I tried to pull the latest code for mshadow and dmlc/cxxnet. However, when I run

    ./build.sh

The build completes but I get the following message at the end

    /usr/bin/ld: skipping incompatible /usr/local/cuda/lib64/../lib/libcudart.so when searching for -lcudart

Could you please help with how I can build successfully. Thanks :)

**Comment by antinucleon** [comment]
That's your cuda configuration problem. I am not able to help you in system admin area...

**Comment by apeeyush** [comment]
I think the issue is because of some breaking changes in V2. I will check it in a few days and would be grateful if you could verify that the code works with the new version.

**Comment by tqchen** [comment]
If you build completes without error, then it is OK. That message simply means you have 32bit cuda library in your searchpath and they skipped it

**Comment by apeeyush** [comment]
@tqchen The build completes without error. Also, I am able to run the MNIST_CONV.conf successfully. However, I am unable to run the kaggle bowl example. I am guessing that this might be because of some breaking changes in V2 since I was able to run the kaggle bowl example around a week ago.

@tqchen @antinucleon  I would be grateful if you could verify that the example still works for you with the latest commits since I am unable to run them now.
