### ISSUE TITLE
compilation problem

### ISSUE THREAD

**Issue by lexbee** [dmlc/cxxnet#7]
Hello everyone. I am having difficulty compiling cxxnet (relatively new to the NN/linux scene). I am running arch 64 bit and I have installed cuda toolkit 6.5 with atlas/lapack. I have installed OpenCV and when I try 'sh build.sh blas=1" I get:

Fetch mshadow...
fatal: destination path 'mshadow' already exists and is not an empty directory.
g++ -c -Wall -g -O3 -msse3 -Wno-unknown-pragmas -funroll-loops -I./mshadow/  -I /usr/local/cuda/include/ -L /usr/local/cuda/lib64/ -pthread -DMSHADOW_USE_MKL=0 -DMSHADOW_USE_CBLAS=1 -o cxxnet_data.o cxxnet/io/cxxnet_data.cpp
In file included from ./mshadow/mshadow/tensor.h:11:0,
                 from cxxnet/io/cxxnet_data.cpp:6:
./mshadow/mshadow/tensor_base.h:83:22: fatal error: cublas.h: No such file or directory
   #include <cublas.h>
                      ^
compilation terminated.
Makefile:34: recipe for target 'cxxnet_data.o' failed
make: **\* [cxxnet_data.o] Error 1

Any advice would be greatly appreciated!

thank you

**Comment by hothHowler** [comment]
Just wanted to quickly add here, the issue lexbee had originally  "undefined reference tocblas_sgemm" could have happened with two different  blas libraries installed. 

I saw this error when I installed 'openblas-devel' 
Using "-I/usr/include/openblas/" and "-lblas" will result in this error message. 
Replacing "-lblas" with "-lopenblas" fixed it for me
