### ISSUE TITLE
compile error

### ISSUE THREAD

**Issue by dzhwinter** [dmlc/cxxnet#71]
nvcc -c -o layer_gpu.o --use_fast_math -g -O3 -ccbin clang++  --std=c++11 -Xcompiler "-DMSHADOW_FORCE_STREAM -Wall -g -O3 -I./mshadow/  -fPIC -msse3 -funroll-loops -Wno-unused-parameter -Wno-unknown-pragmas -I/usr/local/cuda/include -I/opt/intel/mkl/include -DMSHADOW_DIST_PS=1 -std=c++11 -I/home/dzh/Downloads/parameter_server/src -I/home/dzh/Downloads/parameter_server/third_party/include -DCXXNET_USE_OPENCV=1 -DCXXNET_USE_OPENCV_DECODER=1 -I/usr/lib/cudnn -DCXXNET_USE_CUDNN=1 -I/home/dzh/Downloads/parameter_server/src" src/layer/layer_impl.cu
nvcc fatal   : Host compiler targets unsupported OS.
make: *** [layer_gpu.o] Error 1

OS: Linux iripGPU 3.13.0-48-generic #80-Ubuntu SMP Thu Mar 12 11:16:15 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux

nvcc:
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2015 NVIDIA Corporation
Built on Mon_Feb_16_22:59:02_CST_2015
Cuda compilation tools, release 7.0, V7.0.27

clang++:
Ubuntu clang version 3.4-1ubuntu3 (tags/RELEASE_34/final) (based on LLVM 3.4)
Target: x86_64-pc-linux-gnu
Thread model: posix

i change the comiple to g++ and gcc instead of clang++ clang. 
it works well.

**Comment by tqchen** [comment]
This seems to be problem of nvcc instead of cxxnet.
