### ISSUE TITLE
missing libgfortran-3.dll (Windows)

### ISSUE THREAD

**Issue by xinggangw** [dmlc/cxxnet#72]
I can compile and get "cxxnet.exe" on Windows. However, for missing "libgfortran-3.dll", cxxnet can not run. Must I install MinGW to run cxxnet on Windows?

**Comment by antinucleon** [comment]
No. You can download it from openblas.

**Comment by xinggangw** [comment]
Thanks a lot! @antinucleon

I tried different versions of openblas downloaded from github and sourceforge. But I can not find the libgfortran dll at all. Could you provide a linker to download openblas with the libgfortran dll?

**Comment by antinucleon** [comment]
http://sourceforge.net/projects/openblas/files/v0.2.13/
It is mingw64-dll
