### ISSUE TITLE
cxxnet quits silently without producing predictions

### ISSUE THREAD

**Issue by jfkingiii** [dmlc/cxxnet#78]
When I try to run the kaggle bowl example, no predictions are produced and there is no error message:

In batch init.
ThreadBufferIterator: buffer_size=2
ThreadImagePageIterator:image_list=./test.lst,, bin=./test.bin,
loading mean image from models/image_mean.bin
In batch init.
ThreadBufferIterator: buffer_size=2
initializing end, start working

I just cloned the repository yesterday.

**Comment by DataCentric1** [comment]
You must not have the right task name for prediction. Depending on your version one of these could work (I ran into the same problem before).

task = pred_raw
model_in = ./models/xxx.model

or

model_in = ./models/xxx.model
task = extract
extract_node_name = top[-1]
output_format = txt

**Comment by jfkingiii** [comment]
Yes I figured out pred_raw was deprecated in V2. It seems like the documentation should be updated for the tutorial. I was hoping the team would post a higher scoring model now that the competition was over.
