### ISSUE TITLE
help on "extract_feature" task

### ISSUE THREAD

**Issue by mrfipwa** [dmlc/cxxnet#80]
Hi

I have tried to add "task=extract_feature" but didn't get any output. Can you help?

Here is the portion of conf file I am using

------------------------------
pred = pred.txt
iter = mnist
path_img = "./predict_image.gz"
path_label = "./predict_fake_label.gz"
input_flat = 0
iter = end

...

task = extract_feature
extract_node_name = top[-1]
model_in = ../../models/0029.model

-------------------------------

Thanks!

**Comment by mrfipwa** [comment]
after reading the code, I change the task to "extract" and it seems starting producing results.

One more question. What is the .meta file?

**Comment by antinucleon** [comment]
for text output, meta file means nothing. For binary output, meta indicates shape and size.

**Comment by mrfipwa** [comment]
Thanks!
