### ISSUE TITLE
Image mean issue with latest release

### ISSUE THREAD

**Issue by DataCentric1** [dmlc/cxxnet#86]
I'm having this rather odd issue and discovered it by complete accident.

Just cloned the master branch from dmlc today and tried running Kaggle bowl. I had previously run the v2-refactor branch and hence my 'models' folder still had the image mean file from that run. So, I was able to run kaggle bowl and train / val errors looked comparable to what I got with the V2-refactor branch.

Then, I deleted the image mean file and re-ran. It obviously created a new file, but something must be wrong with it as I get pretty high train errors and validation errors are stuck at >0.95 and don't decrease. When I go back and use the older image mean file, things are back to normal. 

Any idea on what the issue could be?

**Comment by antinucleon** [comment]
Thanks for your information. It is very important since we change augmentation part a lot these days. Similar bug report in ImageNet. Could you help me run a quick test by replace ```image_mean=xxxx``` to ```mean_value=255,255,255```?

**Comment by antinucleon** [comment]
Thanks. I think we have located bug commit. We are seeking bug now.

**Comment by DataCentric1** [comment]
Issue looks to be fixed now. Thanks for the quick turnaround!
