### ISSUE TITLE
Please add PredictRaw

### ISSUE THREAD

**Issue by vkuznet** [dmlc/cxxnet#93]
Hi, in previous cxxnet repository (antinucleon/cxxnet) cxxnet was able to generate probabilities via PredictRaw method, in a config user was need to specify pred_raw task. Could you please migrate this functionality into current cxxnet implementation. Thanks, Valentin.

**Comment by winstywang** [comment]
Check this issue: https://github.com/dmlc/cxxnet/issues/64

The task should be extract instead of extract_feature. I will fix the typo in doc today.

**Comment by vkuznet** [comment]
Great, this is exactly what I was looking for, plus ticket indicate how to get values from last layer.
