### ISSUE TITLE
How to import caffe trained model?

### ISSUE THREAD

**Issue by n8744149** [dmlc/cxxnet#94]
Hi, 

Would you like to provide a short example how to load caffe based model and extract its relevant structure and parameters?

Regards,

**Comment by winstywang** [comment]
Caffe converter is under development. Please stay tuned

**Comment by n8744149** [comment]
do you have a dev version so i can use immediately? since it is a bit urgent. thanks in advance

**Comment by winstywang** [comment]
Check it here: https://github.com/huazehuang/cxxnet/commit/3b30b37c9d92145ede831cc5be31f21b439fa4a5 The codes are not fully reviewed now. Just a workaround.

**Comment by n8744149** [comment]
Thanks!
