### ISSUE TITLE
How to do multivariable regression?

### ISSUE THREAD

**Issue by wguo68** [dmlc/cxxnet#97]
Suppose I want to do facial landmark detection.For an image with five landmark,there will be 10 coordinates to learning?  How to set the input data? Do i need to write code for this multivariable regression. I think other people want to know how to sovle the problem with cxxNET.  Thanks.

**Comment by winstywang** [comment]
I will update the doc soon.Stay tuned.

**Comment by winstywang** [comment]
https://github.com/winstywang/cxxnet/blob/master/doc/advanced.md Check the doc here. Hope this will help.

**Comment by wguo68** [comment]
Thank you very much

**Comment by wguo68** [comment]
I follow your instruction, but the program crashed in the code line " Copy(out_.data[top], d.data);" in the function "  virtual bool Next(void)" which was invoked by the code line" while (itr_train->Next()) {" in cxxnet_main.cpp. 
What's wrong with this?

The following is the .conf file:

# example configure file 
# training iterator
data = train
iter = img
    image_list = "./image_list_train.txt"
    image_root = "./data2/train/"
    input_flat = 0
	divideby = 256
    shuffle = 0
iter = end
# evaluation iterator
eval = test
iter = img
    input_flat = 0
    image_list = "./image_list_test.txt"
    image_root = "./data2/test/"
	divideby = 256
    shuffle = 0
iter = end

## global parameters
label_width = 10
label_vec[0,10) = landmarks

netconfig=start
layer[0->1] = conv:cv1
  kernel_size = 3
  pad = 1
  stride = 2
  nchannel = 32
  random_type = xavier
  no_bias=0
layer[1->2] = max_pooling
  kernel_size = 3
  stride = 2
layer[2->3] = flatten
layer[3->3] = dropout
  threshold = 0.5
layer[3->4] = fullc:fc1
  nhidden = 100
  init_sigma = 0.01
layer[4->5] = sigmoid:se1
layer[5->6] = fullc:fc2
  nhidden = 10
  init_sigma = 0.01
layer[6->6] = l2_loss
    target = landmarks
netconfig=end

# input shape not including batch
input_shape = 1,40,40
batch_size = 100

## global parameters
dev = gpu
save_model = 100
max_round = 15
num_round = 15
train_eval = 1
random_type = gaussian
## learning parameters
eta = 0.1
momentum = 0.9
wd  = 0.0
# evaluation metric
metric = error
eval_train = 1
# end of config

**Comment by winstywang** [comment]
Could you please try the case using only one label? It seems the problem is in data iterator, and not related to the multilabel training.

**Comment by wguo68** [comment]
I made a mistake ,the image is 3 channels ,I changed to input_shape to "input_shape = 3,40,40". Now the error gone.

I want to do facial landmark location,for the 40*40 image , would you help to set a suitable train net parameters?  

Thanks.

**Comment by winstywang** [comment]
I have little experience in face related task... I think you may refer to the latest paper in CVPR and arxiv, and adjust their networks based on your data

**Comment by wguo68** [comment]
Okay , I will try.
